% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
  11pt,
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={ASESII 24A02 Project-Based Quiz 1},
  pdfauthor={Group 06: Le Dat Phuc An\_24125052-Pham Nguyen Minh Quan\_24125041-Tran Canh Anh Tuan\_24125048-Vong Chi Van\_24125049},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{ASESII 24A02 Project-Based Quiz 1}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Ridge, Lasso, and Regularization for Neural Features}
\author{Group 06: Le Dat Phuc An\_24125052-Pham Nguyen Minh
Quan\_24125041-Tran Canh Anh Tuan\_24125048-Vong Chi Van\_24125049}
\date{2026-07-17}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section*{Authorship and contribution
statement}\label{authorship-and-contribution-statement}
\addcontentsline{toc}{section}{Authorship and contribution statement}

We confirm that every group member can explain the submitted analysis.
AI use is reported in \texttt{Group06\_AI\_Log.csv}, and the group
checked every AI-assisted item used in this report.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2308}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3077}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2308}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2308}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Student
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
ID
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Main contributions
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Verification performed
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Le Dat Phuc An & 24125052 & Sections 1, 2A, 2B, 5A, and 5B. & Verified
Sections 2D, 3B, and 4C by reproducing results and reviewing the
report. \\
Pham Nguyen Minh Quan & 24125041 & Sections 2D, 2E, 3A, 3B, and 4B. &
Verified Sections 1, 2A, 5A, and 5B by checking methodology, code, and
documentation. \\
Tran Canh Anh Tuan & 24125048 & Sections 2A,2B,3C, 4A, 4C, 4E, 5A. &
Verified Sections 2B, 2C, and 4B by reviewing implementation and
numerical results. \\
Vong Chi Van & 24125049 & Sections 2A,2B,2C, 4A, 4E. & Verified Sections
2E, 3A, and 3C by checking derivations, code, and final outputs. \\
\end{longtable}
}

\section*{Abstract}\label{abstract}
\addcontentsline{toc}{section}{Abstract}

\emph{Maximum 150 words: prediction problem, methods, main evidence, and
recommendation.}

\section*{Reproducible setup}\label{reproducible-setup}
\addcontentsline{toc}{section}{Reproducible setup}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{required\_packages }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"tidyverse"}\NormalTok{, }\StringTok{"glmnet"}\NormalTok{, }\StringTok{"broom"}\NormalTok{, }\StringTok{"knitr"}\NormalTok{)}
\NormalTok{missing\_packages }\OtherTok{\textless{}{-}}\NormalTok{ required\_packages[}
  \SpecialCharTok{!}\FunctionTok{vapply}\NormalTok{(required\_packages, requireNamespace, }\FunctionTok{logical}\NormalTok{(}\DecValTok{1}\NormalTok{), }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{]}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(missing\_packages)) \{}
  \FunctionTok{stop}\NormalTok{(}\StringTok{"Install the required packages before rendering: "}\NormalTok{,}
       \FunctionTok{paste}\NormalTok{(missing\_packages, }\AttributeTok{collapse =} \StringTok{", "}\NormalTok{))}
\NormalTok{\}}

\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(glmnet)}
\FunctionTok{library}\NormalTok{(broom)}
\FunctionTok{library}\NormalTok{(knitr)}

\NormalTok{group\_number }\OtherTok{\textless{}{-}} \FunctionTok{as.integer}\NormalTok{(params}\SpecialCharTok{$}\NormalTok{group\_number)}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(group\_number) }\SpecialCharTok{!=} \DecValTok{1}\DataTypeTok{L} \SpecialCharTok{||} \FunctionTok{is.na}\NormalTok{(group\_number) }\SpecialCharTok{||}\NormalTok{ group\_number }\SpecialCharTok{\textless{}} \DecValTok{1}\DataTypeTok{L}\NormalTok{) \{}
  \FunctionTok{stop}\NormalTok{(}\StringTok{"Set params$group\_number to your assigned positive group number."}\NormalTok{)}
\NormalTok{\}}

\NormalTok{seeds }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}
  \AttributeTok{split =} \DecValTok{240200}\DataTypeTok{L} \SpecialCharTok{+}\NormalTok{ group\_number,}
  \AttributeTok{cv =} \DecValTok{240300}\DataTypeTok{L} \SpecialCharTok{+}\NormalTok{ group\_number,}
  \AttributeTok{features =} \DecValTok{240400}\DataTypeTok{L} \SpecialCharTok{+}\NormalTok{ group\_number}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection*{Shared helper functions}\label{shared-helper-functions}
\addcontentsline{toc}{subsection}{Shared helper functions}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{find\_exam\_data }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(filename) \{}
\NormalTok{  input }\OtherTok{\textless{}{-}}\NormalTok{ knitr}\SpecialCharTok{::}\FunctionTok{current\_input}\NormalTok{(}\AttributeTok{dir =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{  input\_dir }\OtherTok{\textless{}{-}} \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(input) }\SpecialCharTok{\&\&} \FunctionTok{nzchar}\NormalTok{(input)) }\FunctionTok{dirname}\NormalTok{(input) }\ControlFlowTok{else} \FunctionTok{getwd}\NormalTok{()}
\NormalTok{  candidates }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{file.path}\NormalTok{(input\_dir, }\StringTok{"data"}\NormalTok{, filename),}
    \FunctionTok{file.path}\NormalTok{(input\_dir, }\StringTok{".."}\NormalTok{, }\StringTok{"data"}\NormalTok{, filename),}
    \FunctionTok{file.path}\NormalTok{(}\FunctionTok{getwd}\NormalTok{(), }\StringTok{"data"}\NormalTok{, filename)}
\NormalTok{  )}
\NormalTok{  existing }\OtherTok{\textless{}{-}}\NormalTok{ candidates[}\FunctionTok{file.exists}\NormalTok{(candidates)]}
  \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{length}\NormalTok{(existing)) }\FunctionTok{stop}\NormalTok{(}\StringTok{"Cannot locate "}\NormalTok{, filename, }\StringTok{" by a relative path."}\NormalTok{)}
\NormalTok{  hits }\OtherTok{\textless{}{-}} \FunctionTok{unique}\NormalTok{(}\FunctionTok{normalizePath}\NormalTok{(existing, }\AttributeTok{winslash =} \StringTok{"/"}\NormalTok{, }\AttributeTok{mustWork =} \ConstantTok{TRUE}\NormalTok{))}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(hits) }\SpecialCharTok{\textgreater{}} \DecValTok{1}\DataTypeTok{L} \SpecialCharTok{\&\&} \FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(}\FunctionTok{unname}\NormalTok{(tools}\SpecialCharTok{::}\FunctionTok{md5sum}\NormalTok{(hits)))) }\SpecialCharTok{\textgreater{}} \DecValTok{1}\DataTypeTok{L}\NormalTok{) \{}
    \FunctionTok{stop}\NormalTok{(}\StringTok{"Multiple nonidentical copies of "}\NormalTok{, filename, }\StringTok{" were found."}\NormalTok{)}
\NormalTok{  \}}
\NormalTok{  hits[[}\DecValTok{1}\DataTypeTok{L}\NormalTok{]]}
\NormalTok{\}}

\NormalTok{split\_rows }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(n, }\AttributeTok{train\_prop =} \FloatTok{0.80}\NormalTok{, seed) \{}
  \FunctionTok{stopifnot}\NormalTok{(n }\SpecialCharTok{\textgreater{}=} \DecValTok{10}\DataTypeTok{L}\NormalTok{, train\_prop }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, train\_prop }\SpecialCharTok{\textless{}} \DecValTok{1}\NormalTok{)}
  \FunctionTok{set.seed}\NormalTok{(seed)}
\NormalTok{  train }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(}\FunctionTok{sample.int}\NormalTok{(n, }\FunctionTok{floor}\NormalTok{(train\_prop }\SpecialCharTok{*}\NormalTok{ n), }\AttributeTok{replace =} \ConstantTok{FALSE}\NormalTok{))}
  \FunctionTok{list}\NormalTok{(}\AttributeTok{train =}\NormalTok{ train, }\AttributeTok{test =} \FunctionTok{setdiff}\NormalTok{(}\FunctionTok{seq\_len}\NormalTok{(n), train))}
\NormalTok{\}}

\NormalTok{fit\_scaler }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x, }\AttributeTok{tol =} \FloatTok{1e{-}12}\NormalTok{) \{}
\NormalTok{  x }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(x)}
\NormalTok{  center }\OtherTok{\textless{}{-}} \FunctionTok{colMeans}\NormalTok{(x)}
\NormalTok{  centered }\OtherTok{\textless{}{-}} \FunctionTok{sweep}\NormalTok{(x, }\DecValTok{2}\DataTypeTok{L}\NormalTok{, center, }\StringTok{"{-}"}\NormalTok{)}
\NormalTok{  scale }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{colMeans}\NormalTok{(centered}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\NormalTok{  keep }\OtherTok{\textless{}{-}} \FunctionTok{is.finite}\NormalTok{(scale) }\SpecialCharTok{\&}\NormalTok{ scale }\SpecialCharTok{\textgreater{}}\NormalTok{ tol}
  \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{any}\NormalTok{(keep)) }\FunctionTok{stop}\NormalTok{(}\StringTok{"No nonconstant training predictor remains."}\NormalTok{)}
  \FunctionTok{list}\NormalTok{(}
    \AttributeTok{center =}\NormalTok{ center[keep],}
    \AttributeTok{scale =}\NormalTok{ scale[keep],}
    \AttributeTok{keep =}\NormalTok{ keep,}
    \AttributeTok{dropped =} \FunctionTok{colnames}\NormalTok{(x)[}\SpecialCharTok{!}\NormalTok{keep]}
\NormalTok{  )}
\NormalTok{\}}

\NormalTok{apply\_scaler }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x, prep) \{}
\NormalTok{  x }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(x)[, prep}\SpecialCharTok{$}\NormalTok{keep, drop }\OtherTok{=} \ConstantTok{FALSE}\NormalTok{]}
\NormalTok{  x }\OtherTok{\textless{}{-}} \FunctionTok{sweep}\NormalTok{(x, }\DecValTok{2}\DataTypeTok{L}\NormalTok{, prep}\SpecialCharTok{$}\NormalTok{center, }\StringTok{"{-}"}\NormalTok{)}
  \FunctionTok{sweep}\NormalTok{(x, }\DecValTok{2}\DataTypeTok{L}\NormalTok{, prep}\SpecialCharTok{$}\NormalTok{scale, }\StringTok{"/"}\NormalTok{)}
\NormalTok{\}}

\NormalTok{make\_foldid }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(n, }\AttributeTok{k =} \DecValTok{5}\DataTypeTok{L}\NormalTok{, seed) \{}
  \ControlFlowTok{if}\NormalTok{ (k }\SpecialCharTok{\textless{}} \DecValTok{3}\DataTypeTok{L} \SpecialCharTok{||}\NormalTok{ k }\SpecialCharTok{\textgreater{}}\NormalTok{ n) }\FunctionTok{stop}\NormalTok{(}\StringTok{"Require 3 \textless{}= k \textless{}= number of training rows."}\NormalTok{)}
  \FunctionTok{set.seed}\NormalTok{(seed)}
  \FunctionTok{sample}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\FunctionTok{seq\_len}\NormalTok{(k), }\AttributeTok{length.out =}\NormalTok{ n))}
\NormalTok{\}}

\NormalTok{fit\_cv\_glmnet }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x, y, alpha, foldid) \{}
\NormalTok{  glmnet}\SpecialCharTok{::}\FunctionTok{cv.glmnet}\NormalTok{(}
    \AttributeTok{x =}\NormalTok{ x,}
    \AttributeTok{y =}\NormalTok{ y,}
    \AttributeTok{family =} \StringTok{"gaussian"}\NormalTok{,}
    \AttributeTok{alpha =}\NormalTok{ alpha,}
    \AttributeTok{foldid =}\NormalTok{ foldid,}
    \AttributeTok{standardize =} \ConstantTok{FALSE}\NormalTok{,}
    \AttributeTok{intercept =} \ConstantTok{TRUE}\NormalTok{,}
    \AttributeTok{type.measure =} \StringTok{"mse"}
\NormalTok{  )}
\NormalTok{\}}

\NormalTok{score\_regression }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(y, prediction) \{}
\NormalTok{  y }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(y)}
\NormalTok{  prediction }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(prediction)}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(y) }\SpecialCharTok{!=} \FunctionTok{length}\NormalTok{(prediction) }\SpecialCharTok{||} \FunctionTok{any}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.finite}\NormalTok{(}\FunctionTok{c}\NormalTok{(y, prediction)))) \{}
    \FunctionTok{stop}\NormalTok{(}\StringTok{"Metrics require equal{-}length finite vectors."}\NormalTok{)}
\NormalTok{  \}}
  \FunctionTok{c}\NormalTok{(}\AttributeTok{RMSE =} \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{((y }\SpecialCharTok{{-}}\NormalTok{ prediction)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)),}
    \AttributeTok{MAE =} \FunctionTok{mean}\NormalTok{(}\FunctionTok{abs}\NormalTok{(y }\SpecialCharTok{{-}}\NormalTok{ prediction)))}
\NormalTok{\}}

\NormalTok{count\_nonzero }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(fit, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{, }\AttributeTok{tol =} \FloatTok{1e{-}8}\NormalTok{) \{}
\NormalTok{  b }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(stats}\SpecialCharTok{::}\FunctionTok{coef}\NormalTok{(fit, }\AttributeTok{s =}\NormalTok{ s))}
\NormalTok{  slopes }\OtherTok{\textless{}{-}}\NormalTok{ b[}\FunctionTok{rownames}\NormalTok{(b) }\SpecialCharTok{!=} \StringTok{"(Intercept)"}\NormalTok{, }\DecValTok{1}\DataTypeTok{L}\NormalTok{]}
  \FunctionTok{sum}\NormalTok{(}\FunctionTok{abs}\NormalTok{(slopes) }\SpecialCharTok{\textgreater{}}\NormalTok{ tol)}
\NormalTok{\}}

\NormalTok{safe\_condition\_numbers }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x, lambda, }\AttributeTok{tol =} \FloatTok{1e{-}10}\NormalTok{) \{}
\NormalTok{  G }\OtherTok{\textless{}{-}} \FunctionTok{crossprod}\NormalTok{(x) }\SpecialCharTok{/} \FunctionTok{nrow}\NormalTok{(x)}
\NormalTok{  eigenvalues }\OtherTok{\textless{}{-}} \FunctionTok{eigen}\NormalTok{(G, }\AttributeTok{symmetric =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{only.values =} \ConstantTok{TRUE}\NormalTok{)}\SpecialCharTok{$}\NormalTok{values}
\NormalTok{  largest }\OtherTok{\textless{}{-}} \FunctionTok{max}\NormalTok{(eigenvalues)}
\NormalTok{  smallest }\OtherTok{\textless{}{-}} \FunctionTok{max}\NormalTok{(}\FunctionTok{min}\NormalTok{(eigenvalues), }\DecValTok{0}\NormalTok{)}
\NormalTok{  cutoff }\OtherTok{\textless{}{-}}\NormalTok{ tol }\SpecialCharTok{*} \FunctionTok{max}\NormalTok{(}\DecValTok{1}\NormalTok{, largest)}
  \FunctionTok{c}\NormalTok{(}
    \AttributeTok{gram =} \ControlFlowTok{if}\NormalTok{ (smallest }\SpecialCharTok{\textless{}=}\NormalTok{ cutoff) }\ConstantTok{Inf} \ControlFlowTok{else}\NormalTok{ largest }\SpecialCharTok{/}\NormalTok{ smallest,}
    \AttributeTok{ridge =}\NormalTok{ (largest }\SpecialCharTok{+}\NormalTok{ lambda) }\SpecialCharTok{/}\NormalTok{ (smallest }\SpecialCharTok{+}\NormalTok{ lambda)}
\NormalTok{  )}
\NormalTok{\}}
\NormalTok{plot\_model\_result }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(model, model\_name) \{ }
\NormalTok{   model\_result }\OtherTok{\textless{}{-}} \FunctionTok{augment}\NormalTok{(model)}
  \FunctionTok{ggplot}\NormalTok{(model\_result, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ .fitted, }\AttributeTok{y =}\NormalTok{ .resid)) }\SpecialCharTok{+}
    \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"steelblue"}\NormalTok{, }\AttributeTok{size =} \DecValTok{2}\NormalTok{, }\AttributeTok{alpha =} \FloatTok{0.8}\NormalTok{) }\SpecialCharTok{+}
    
    \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
    
    \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}

    \FunctionTok{labs}\NormalTok{(}
      \AttributeTok{title =} \FunctionTok{paste}\NormalTok{(}\StringTok{"Residual Plot Model:"}\NormalTok{, model\_name),}
      \AttributeTok{subtitle =} \StringTok{"Checking for non{-}linear patterns and constant variance"}\NormalTok{,}
      \AttributeTok{x =} \StringTok{"Predicted lpsa (.fitted)"}\NormalTok{,}
      \AttributeTok{y =} \StringTok{"Residuals (.resid)"}
\NormalTok{    ) }
\NormalTok{\}}

\NormalTok{vif\_manual }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(model) \{}
\NormalTok{  X }\OtherTok{\textless{}{-}} \FunctionTok{model.matrix}\NormalTok{(model)[, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, drop }\OtherTok{=} \ConstantTok{FALSE}\NormalTok{]}

  \FunctionTok{sapply}\NormalTok{(}\FunctionTok{seq\_len}\NormalTok{(}\FunctionTok{ncol}\NormalTok{(X)), }\ControlFlowTok{function}\NormalTok{(i) \{}
\NormalTok{    fit }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(X[, i] }\SpecialCharTok{\textasciitilde{}}\NormalTok{ X[, }\SpecialCharTok{{-}}\NormalTok{i])}
    \DecValTok{1} \SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{summary}\NormalTok{(fit)}\SpecialCharTok{$}\NormalTok{r.squared)}
\NormalTok{  \}) }\SpecialCharTok{|\textgreater{}} \FunctionTok{setNames}\NormalTok{(}\FunctionTok{colnames}\NormalTok{(X))}
\NormalTok{\}}

\NormalTok{coef\_norm }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(coefs) \{}
\NormalTok{  b }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(coefs)}
  \FunctionTok{sqrt}\NormalTok{(}\FunctionTok{sum}\NormalTok{(b[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, ]}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{))}
\NormalTok{\}}

\NormalTok{nonzero\_slopes }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(coefs, }\AttributeTok{tol =} \FloatTok{1e{-}8}\NormalTok{) \{}
\NormalTok{  b }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(coefs)}
  \FunctionTok{sum}\NormalTok{(}\FunctionTok{abs}\NormalTok{(b[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, ]) }\SpecialCharTok{\textgreater{}}\NormalTok{ tol)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\section{Problem 1. Prediction design and leakage
control}\label{problem-1.-prediction-design-and-leakage-control}

\subsection{1A. Target and predictors}\label{a.-target-and-predictors}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{config }\OtherTok{\textless{}{-}} \ControlFlowTok{if}\NormalTok{ (group\_number }\SpecialCharTok{\%\%} \DecValTok{2}\DataTypeTok{L} \SpecialCharTok{==} \DecValTok{1}\DataTypeTok{L}\NormalTok{) \{}
  \FunctionTok{list}\NormalTok{(}
    \AttributeTok{file =} \StringTok{"fat.csv"}\NormalTok{,}
    \AttributeTok{response =} \StringTok{"brozek"}\NormalTok{,}
    \AttributeTok{excluded =} \FunctionTok{c}\NormalTok{(}\StringTok{"brozek"}\NormalTok{, }\StringTok{"siri"}\NormalTok{, }\StringTok{"density"}\NormalTok{, }\StringTok{"free"}\NormalTok{)}
\NormalTok{  )}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{list}\NormalTok{(}
    \AttributeTok{file =} \StringTok{"prostate.csv"}\NormalTok{,}
    \AttributeTok{response =} \StringTok{"lpsa"}\NormalTok{,}
    \AttributeTok{excluded =} \StringTok{"lpsa"}
\NormalTok{  )}
\NormalTok{\}}

\NormalTok{data\_raw }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\FunctionTok{find\_exam\_data}\NormalTok{(config}\SpecialCharTok{$}\NormalTok{file), }\AttributeTok{check.names =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{predictors }\OtherTok{\textless{}{-}} \FunctionTok{setdiff}\NormalTok{(}\FunctionTok{names}\NormalTok{(data\_raw), config}\SpecialCharTok{$}\NormalTok{excluded)}
\NormalTok{analysis\_data }\OtherTok{\textless{}{-}}\NormalTok{ data\_raw[, }\FunctionTok{c}\NormalTok{(config}\SpecialCharTok{$}\NormalTok{response, predictors), drop }\OtherTok{=} \ConstantTok{FALSE}\NormalTok{]}

\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{anyNA}\NormalTok{(analysis\_data)) }\FunctionTok{stop}\NormalTok{(}\StringTok{"Declare a training{-}only missing{-}value plan."}\NormalTok{)}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{all}\NormalTok{(}\FunctionTok{vapply}\NormalTok{(analysis\_data, is.numeric, }\FunctionTok{logical}\NormalTok{(}\DecValTok{1}\NormalTok{)))) \{}
  \FunctionTok{stop}\NormalTok{(}\StringTok{"The assigned response and predictors must be numeric."}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\emph{Define the prediction task and justify every exclusion.}

\subsubsection{\texorpdfstring{1. Response =
\(lpsa\)}{1. Response = lpsa}}\label{response-lpsa}

\(lpsa\) measures the natural Logarithm of Prostate-Specific Antigen,
which is a continuous number

\subsubsection{2. Candidate Predictors}\label{candidate-predictors}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2917}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.4306}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.2778}}@{}}
\toprule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Candidate Predictors & Full Name & Type \\
lcavol & Log Cancer Volume & Continuous \\
lweight & Log Prostate Weight & Continuous \\
age & Age & Continuous \\
lbph & Log Benign Prostatic Hyperplasia & Continuous \\
svi & Seminal Vesicle Invasion & Binary (0 / 1) \\
lcp & Log Capsular Penetration & Continuous \\
gleason & Gleason Score & Ordered Categorical \\
pgg45 & Percentage Gleason Grade 4/5 & Continuous (0--100) \\
\end{longtable}
}

\subsubsection{3. Unit of Observation}\label{unit-of-observation}

Each row of the dataset contains the information of a radical
prostactomy treated patient which comprises of the target and the
predictors values.

\subsubsection{4. Study Population}\label{study-population}

The dataset contains 97 patients aged 41 to 79 with clinically localized
adenocarcinoma who went through radical prostactomy at Stanford
University Center by Dr.~Thomas A. Stamey and his surgical team during
the late 1980s.

\subsubsection{5. Prediction Objective}\label{prediction-objective}

To build a regression model that predicts the log prostate-specific
antigen level (lpsa) using the clinical variables (lcavol, lweight, age,
lbph, svi, lcp, gleason, and pgg45).

\subsubsection{6. Dataset Source}\label{dataset-source}

\url{https://sci-hub.sg/storage/2024/6429/4cbb75646440af614abced23a70ba059/stamey1989.pdf}

\subsubsection{7. Required Exclusions}\label{required-exclusions}

The response variable, \texttt{lpsa}, was excluded from the predictor
matrix because it is the outcome to be predicted. The remaining eight
clinical variables were retained as predictors. Since the dataset
contains no variables derived from \texttt{lpsa}, no additional
exclusions were required. This prevents target leakage and ensures a
fair comparison among the regression models.

\subsection{1B. Split and train-only
preprocessing}\label{b.-split-and-train-only-preprocessing}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{split }\OtherTok{\textless{}{-}} \FunctionTok{split\_rows}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(analysis\_data), }\AttributeTok{seed =}\NormalTok{ seeds}\SpecialCharTok{$}\NormalTok{split)}
\NormalTok{train\_id }\OtherTok{\textless{}{-}}\NormalTok{ split}\SpecialCharTok{$}\NormalTok{train}
\NormalTok{test\_id }\OtherTok{\textless{}{-}}\NormalTok{ split}\SpecialCharTok{$}\NormalTok{test}

\NormalTok{x\_raw }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(analysis\_data[, predictors, }\AttributeTok{drop =} \ConstantTok{FALSE}\NormalTok{])}
\NormalTok{y\_raw }\OtherTok{\textless{}{-}}\NormalTok{ analysis\_data[[config}\SpecialCharTok{$}\NormalTok{response]]}

\NormalTok{x\_prep }\OtherTok{\textless{}{-}} \FunctionTok{fit\_scaler}\NormalTok{(x\_raw[train\_id, , }\AttributeTok{drop =} \ConstantTok{FALSE}\NormalTok{])}
\NormalTok{x\_train }\OtherTok{\textless{}{-}} \FunctionTok{apply\_scaler}\NormalTok{(x\_raw[train\_id, , }\AttributeTok{drop =} \ConstantTok{FALSE}\NormalTok{], x\_prep)}
\NormalTok{x\_test }\OtherTok{\textless{}{-}} \FunctionTok{apply\_scaler}\NormalTok{(x\_raw[test\_id, , }\AttributeTok{drop =} \ConstantTok{FALSE}\NormalTok{], x\_prep)}
\NormalTok{y\_train }\OtherTok{\textless{}{-}}\NormalTok{ y\_raw[train\_id]}
\NormalTok{y\_test }\OtherTok{\textless{}{-}}\NormalTok{ y\_raw[test\_id]}

\NormalTok{foldid }\OtherTok{\textless{}{-}} \FunctionTok{make\_foldid}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(x\_train), }\AttributeTok{k =} \DecValTok{5}\DataTypeTok{L}\NormalTok{, }\AttributeTok{seed =}\NormalTok{ seeds}\SpecialCharTok{$}\NormalTok{cv)}
\end{Highlighting}
\end{Shaded}

\emph{Report seeds, dimensions, scaling, folds, and leakage safeguards.}

\subsubsection{1. Split seed}\label{split-seed}

\begin{itemize}
\tightlist
\item
  Seed \texttt{split} for 80/20 split: 240206
\item
  Seed \texttt{cv} for K-fold split: 240306
\end{itemize}

\subsubsection{2. Train/Test Split}\label{traintest-split}

The dataset of 97 observations was partitioned into:

\begin{itemize}
\tightlist
\item
  \textbf{Training Set:} 77 observations
\item
  \textbf{Test Set:} 20 observations
\end{itemize}

\subsubsection{3. Feature Scaling Rule}\label{feature-scaling-rule}

Continuous predictor variables were centered and scaled using the helper
functions \texttt{fit\_scaler()} and \texttt{apply\_scaler()}. The
scaling parameters were estimated \textbf{only from the training data}
in \texttt{fit\_scaler()} and then applied unchanged to both the
training and test sets by \texttt{apply\_scaler()}.

Specifically, each predictor was transformed as \[x_{\text{scaled}} =
\frac{x - \bar{x}_{\text{train}}}
{\sqrt{\frac{1}{n_{\text{train}}} \sum_{i=1}^{n_{\text{train}}} (x_i - \bar{x}_{\text{train}})^2}},\]
where \(\bar{x}_{\text{train}}\) is the mean of the predictor in the
training set, and the denominator is the population standard deviation
computed from the training observations. Using the same scaling
parameters for the test set prevents information leakage from the
holdout data.

\subsubsection{4. Five-Fold Assignment
Rule}\label{five-fold-assignment-rule}

A single, immutable five-fold cross-validation assignment vector
(\texttt{foldid}) was generated on the 77 training observations using
the designated \texttt{cv} random seed. To ensure fair and controlled
comparisons, this exact same fold assignment was reused across all
models evaluated:

\begin{itemize}
\tightlist
\item
  Ridge Regression
\item
  Lasso Regression
\item
  Elastic Net
\item
  All subsequent hyperparameter grid evaluations
\end{itemize}

\subsubsection{5. Missing-Value Plan}\label{missing-value-plan}

No missing values were detected. If any had been present, they would
have been handled using a training-only imputation procedure before
model fitting.

\subsection{1C. Training-data
exploration}\label{c.-training-data-exploration}

The exploratory analysis in this section uses only the training
observations to avoid information leakage from the holdout test set.

\subsubsection{Response distribution}\label{response-distribution}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(y\_train)}
\FunctionTok{sd}\NormalTok{(y\_train)}

\FunctionTok{hist}\NormalTok{(}
\NormalTok{  y\_train,}
  \AttributeTok{main =} \StringTok{"Histogram of y\_train"}\NormalTok{,}
  \AttributeTok{xlab =} \StringTok{"y\_train"}
\NormalTok{)}

\FunctionTok{qqnorm}\NormalTok{(y\_train)}
\FunctionTok{qqline}\NormalTok{(y\_train)}
\end{Highlighting}
\end{Shaded}

The response variable (\texttt{lpsa}) has a mean of \textbf{2.54} and a
median of \textbf{2.59}, indicating an approximately symmetric
distribution. Most observations lie between \textbf{1.73} (first
quartile) and \textbf{3.28} (third quartile), with a standard deviation
of \textbf{1.15}.

The histogram suggests that most observations are concentrated around
the center, while only a few observations appear in the lower and upper
tails. The normal Q--Q plot shows that most observations follow the
reference line reasonably well, with slight departures in the tails.
Overall, the response distribution is approximately normal, making it
suitable for linear regression.

\subsubsection{Relationship exploration}\label{relationship-exploration}

\paragraph{Scatterplot matrix}\label{scatterplot-matrix}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pairs}\NormalTok{(}
\NormalTok{  analysis\_data[train\_id, ],}
  \AttributeTok{pch =} \DecValTok{20}\NormalTok{,}
  \AttributeTok{cex =} \FloatTok{0.6}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The scatterplot matrix provides a visual overview of pairwise
relationships among the response and predictors. Several predictors
exhibit approximately linear relationships with the response,
particularly \texttt{lcavol}. Strong positive associations are also
visible between several predictor pairs, suggesting that some variables
may contain overlapping information.

\paragraph{Correlation matrix}\label{correlation-matrix}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cor\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(analysis\_data[train\_id, ])}

\NormalTok{heatmap\_df }\OtherTok{\textless{}{-}} \FunctionTok{expand.grid}\NormalTok{(}
  \AttributeTok{Var1 =} \FunctionTok{rownames}\NormalTok{(cor\_matrix),}
  \AttributeTok{Var2 =} \FunctionTok{colnames}\NormalTok{(cor\_matrix)}
\NormalTok{)}

\NormalTok{heatmap\_df}\SpecialCharTok{$}\NormalTok{value }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(cor\_matrix)}

\FunctionTok{ggplot}\NormalTok{(heatmap\_df, }\FunctionTok{aes}\NormalTok{(Var1, Var2, }\AttributeTok{fill =}\NormalTok{ value)) }\SpecialCharTok{+}
  \FunctionTok{geom\_tile}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =} \FunctionTok{round}\NormalTok{(value, }\DecValTok{2}\NormalTok{)), }\AttributeTok{size =} \DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_gradient2}\NormalTok{(}
    \AttributeTok{low =} \StringTok{"blue"}\NormalTok{,}
    \AttributeTok{mid =} \StringTok{"white"}\NormalTok{,}
    \AttributeTok{high =} \StringTok{"red"}\NormalTok{,}
    \AttributeTok{midpoint =} \DecValTok{0}\NormalTok{,}
    \AttributeTok{limits =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{)}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{coord\_fixed}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

The correlation heatmap shows that \textbf{lcavol} has the strongest
linear relationship with the response (\emph{r} = 0.75), indicating that
tumor volume is the single most informative predictor of \texttt{lpsa}.
Moderate positive correlations are also observed for \textbf{lcp}
(\emph{r} = 0.59) and \textbf{svi} (\emph{r} = 0.58), whereas
\texttt{age}, \texttt{lbph}, and \texttt{lweight} exhibit relatively
weak marginal correlations with the response.

\subsubsection{Potential
multicollinearity}\label{potential-multicollinearity}

The correlation matrix indicates several moderately to strongly
correlated predictor pairs.

The strongest pairwise correlations include

\begin{itemize}
\tightlist
\item
  \texttt{gleason} and \texttt{pgg45} (\textbf{r = 0.76}),
\item
  \texttt{lcavol} and \texttt{lcp} (\textbf{r = 0.73}),
\item
  \texttt{lcp} and \texttt{svi} (\textbf{r = 0.67}),
\item
  \texttt{lcavol} and \texttt{svi} (\textbf{r = 0.59}),
\item
  \texttt{lcavol} and \texttt{gleason} (\textbf{r = 0.47}).
\end{itemize}

These relationships suggest that some predictors may contain overlapping
information. However, pairwise correlation alone does not imply severe
multicollinearity, since multicollinearity depends on the joint linear
relationship among all predictors rather than individual pairs.
Therefore, formal diagnostics such as the variance inflation factor
(VIF) will be performed after fitting the OLS model to determine whether
coefficient instability is present.

\subsubsection{One possible anomaly or influential
observation}\label{one-possible-anomaly-or-influential-observation}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(analysis\_data[train\_id, ])}
\end{Highlighting}
\end{Shaded}

The boxplots identify several potential outliers, particularly in
\textbf{age} and \textbf{pgg45}. Among the predictors, \texttt{pgg45}
exhibits the largest variability, while \texttt{age} contains several
observations outside the whiskers. These observations are retained
because there is no evidence that they result from data entry errors.

\subsubsection{Question for regularized
models}\label{question-for-regularized-models}

Based on the exploratory analysis, the following question will guide the
remaining analysis:

\begin{quote}
Can regularization improve predictive performance and coefficient
stability when predictors contain overlapping information?
\end{quote}

\emph{Interpret multicollinearity, one anomaly, and the question
regularization will address.}

\section{Problem 2. OLS, ridge, and
lasso}\label{problem-2.-ols-ridge-and-lasso}

\subsection{2A. OLS baseline}\label{a.-ols-baseline}

The ordinary least squares (OLS) model was fitted using only the
standardized training observations. Throughout this section, the holdout
test set remained completely untouched to ensure a fair comparison with
the regularized regression models.

\subsubsection{Fit OLS}\label{fit-ols}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x\_train\_df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(x\_train)}
\NormalTok{x\_train\_df}\SpecialCharTok{$}\NormalTok{lpsa }\OtherTok{\textless{}{-}}\NormalTok{ y\_train}

\NormalTok{ols\_model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lpsa }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ x\_train\_df)}
\end{Highlighting}
\end{Shaded}

The fitted OLS model serves as the baseline model for all subsequent
comparisons with ridge and lasso regression.

\subsubsection{Coefficient estimates}\label{coefficient-estimates}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(ols\_model)}
\end{Highlighting}
\end{Shaded}

The fitted OLS model is statistically significant overall (\textbf{F =
15.78}, p \textless{} 0.001), indicating that at least one predictor
contributes to explaining the variation in the response variable.

The model achieves a \textbf{Multiple} \(R^2\) of 0.6500 and an
\textbf{Adjusted} \(R^2\) of 0.6088, suggesting that approximately
\textbf{65\%} of the variability in \texttt{lpsa} is explained by the
eight clinical predictors.

Among the predictors,

\begin{itemize}
\tightlist
\item
  \textbf{lcavol} (\(\beta=0.674\), p \textless{} 0.001),
\item
  \textbf{lweight} (\(\beta=0.202\), p = 0.0438),
\item
  \textbf{age} (\(\beta=-0.194\), p = 0.0435), and
\item
  \textbf{svi} (\(\beta=0.282\), p = 0.0206)
\end{itemize}

are statistically significant at the 5\% significance level.

The remaining predictors (\texttt{lbph}, \texttt{lcp}, \texttt{gleason},
and \texttt{pgg45}) are not individually significant after adjusting for
the other predictors in the model.

The estimated coefficient for \textbf{age} is negative
(\(\beta=-0.194\)). This result suggests that the estimated effect of
\texttt{age} changes after accounting for the remaining predictors in
the model. The possibility of correlation among predictors is therefore
investigated using variance inflation factors in the following
subsection.

\subsubsection{Training error}\label{training-error}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train\_pred }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(ols\_model)}

\NormalTok{train\_mse }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{((y\_train }\SpecialCharTok{{-}}\NormalTok{ train\_pred)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{train\_rmse }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(train\_mse)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Training MSE :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(train\_mse, }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Training RMSE:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(train\_rmse, }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The fitted OLS model achieved

\begin{itemize}
\tightlist
\item
  \textbf{Training MSE = 0.4544}
\item
  \textbf{Training RMSE = 0.6741}
\end{itemize}

These quantities measure the goodness-of-fit on the training
observations used to estimate the regression coefficients. Since the
model is evaluated on the same data used for fitting, the training error
is expected to underestimate the prediction error on unseen
observations.

\subsubsection{Five-fold
cross-validation}\label{five-fold-cross-validation}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cv\_mse }\OtherTok{\textless{}{-}} \FunctionTok{numeric}\NormalTok{(}\DecValTok{5}\NormalTok{)}
\NormalTok{coefs\_list }\OtherTok{\textless{}{-}}\FunctionTok{list}\NormalTok{()}
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{)\{}

\NormalTok{  train\_fold }\OtherTok{\textless{}{-}}\NormalTok{ x\_train\_df[foldid }\SpecialCharTok{!=}\NormalTok{ i, ]}
\NormalTok{  valid\_fold }\OtherTok{\textless{}{-}}\NormalTok{ x\_train\_df[foldid }\SpecialCharTok{==}\NormalTok{ i, ]}

\NormalTok{  model }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(lpsa }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ train\_fold)}

\NormalTok{  pred }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(model, }\AttributeTok{newdata =}\NormalTok{ valid\_fold)}
\NormalTok{  fold\_coef }\OtherTok{\textless{}{-}} \FunctionTok{as.matrix}\NormalTok{(}\FunctionTok{coef}\NormalTok{(model, }\AttributeTok{s=}\StringTok{"lambda.min"}\NormalTok{))}
\NormalTok{  coefs\_list[[i]] }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(}\FunctionTok{t}\NormalTok{(fold\_coef))}
\NormalTok{  cv\_mse[i] }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{((valid\_fold}\SpecialCharTok{$}\NormalTok{lpsa }\SpecialCharTok{{-}}\NormalTok{ pred)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{\}}
\NormalTok{coef\_ols\_df }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(coefs\_list)}
\NormalTok{cv\_table }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Fold =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{,}
  \AttributeTok{Validation\_MSE =} \FunctionTok{round}\NormalTok{(cv\_mse, }\DecValTok{4}\NormalTok{)}
\NormalTok{)}

\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(cv\_table)}
\end{Highlighting}
\end{Shaded}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}rr@{}}
\toprule\noalign{}
Fold & Validation\_MSE \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
1 & 0.8259 \\
2 & 0.8568 \\
3 & 0.4011 \\
4 & 0.4893 \\
5 & 0.9002 \\
\end{longtable}
}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Mean CV MSE :"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(cv\_mse), }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Mean CV MSE : 0.6947
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Mean CV RMSE:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(}\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{mean}\NormalTok{(cv\_mse)), }\DecValTok{4}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Mean CV RMSE: 0.8335
\end{verbatim}

The validation errors obtained from the five folds are

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}rr@{}}
\toprule\noalign{}
Fold & Validation MSE \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
1 & 0.8259 \\
2 & 0.8568 \\
3 & 0.4011 \\
4 & 0.4893 \\
5 & 0.9002 \\
\end{longtable}
}

The average cross-validation error is

\begin{itemize}
\tightlist
\item
  \textbf{Mean CV MSE = 0.6947}
\item
  \textbf{Mean CV RMSE = 0.8335}
\end{itemize}

As expected, the cross-validation error is larger than the training
error because each validation fold consists of observations that were
not used to estimate the regression coefficients. Although some
variation exists among the five folds, the validation errors remain
within a similar range, suggesting that the predictive performance of
the OLS model is reasonably stable across different training subsets.

\subsubsection{Residual diagnostics}\label{residual-diagnostics}

\paragraph{Residual versus fitted
values}\label{residual-versus-fitted-values}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}
  \FunctionTok{fitted}\NormalTok{(ols\_model),}
  \FunctionTok{resid}\NormalTok{(ols\_model),}
  \AttributeTok{xlab =} \StringTok{"Fitted values"}\NormalTok{,}
  \AttributeTok{ylab =} \StringTok{"Residuals"}\NormalTok{,}
  \AttributeTok{main =} \StringTok{"Residuals vs Fitted"}
\NormalTok{)}

\FunctionTok{abline}\NormalTok{(}\AttributeTok{h =} \DecValTok{0}\NormalTok{, }\AttributeTok{col =} \StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The residual-versus-fitted plot shows that the residuals are randomly
scattered around zero without noticeable curvature or funnel-shaped
patterns. This suggests that the assumptions of

\begin{itemize}
\tightlist
\item
  linearity, and
\item
  constant error variance (homoscedasticity)
\end{itemize}

are reasonably satisfied. No obvious systematic pattern indicating model
misspecification is observed.

\paragraph{Normal Q-Q plot}\label{normal-q-q-plot}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(}\FunctionTok{resid}\NormalTok{(ols\_model))}
\FunctionTok{qqline}\NormalTok{(}\FunctionTok{resid}\NormalTok{(ols\_model), }\AttributeTok{col =} \StringTok{"red"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The normal Q-Q plot indicates that most residuals lie close to the
reference line, with only slight departures in the two tails. Therefore,
the residual distribution appears approximately normal.

The normal Q--Q plot indicates that the residuals are approximately
normally distributed, with only slight deviations in the tails. This
behavior is consistent with the mildly skewed response distribution
observed during the exploratory analysis. Since the residuals satisfy

\[\hat{\mathbf e}=(I-H)\mathbf y,\]

where \(\hat{\mathbf e}\) is the residual vector, \(\mathbf y\) is the
response vector, \(I\) is the identity matrix, and
\(H=X(X^\top X)^{-1}X^\top\) is the hat matrix, their distribution
naturally reflects the response after removing the fitted linear
component. Overall, there is no strong evidence against the normality
assumption.

\paragraph{Influence plot}\label{influence-plot}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(ols\_model, }\AttributeTok{which =} \DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Most observations have low leverage and moderate residuals. Although a
few observations (e.g., 23, 37, and 54) stand out slightly, none appears
to have an unusually large influence on the fitted model.

\paragraph{Cook's Distance}\label{cooks-distance}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cook }\OtherTok{\textless{}{-}} \FunctionTok{cooks.distance}\NormalTok{(ols\_model)}

\FunctionTok{plot}\NormalTok{(}
\NormalTok{  cook,}
  \AttributeTok{type =} \StringTok{"h"}\NormalTok{,}
  \AttributeTok{lwd =} \DecValTok{3}\NormalTok{,}
  \AttributeTok{col =} \StringTok{"red"}\NormalTok{,}
  \AttributeTok{xlab =} \StringTok{"Observation"}\NormalTok{,}
  \AttributeTok{ylab =} \StringTok{"Cook\textquotesingle{}s Distance"}\NormalTok{,}
  \AttributeTok{main =} \StringTok{"Cook\textquotesingle{}s Distance"}
\NormalTok{)}

\FunctionTok{abline}\NormalTok{(}
  \AttributeTok{h =} \DecValTok{4} \SpecialCharTok{/} \FunctionTok{nrow}\NormalTok{(x\_train\_df),}
  \AttributeTok{col =} \StringTok{"blue"}\NormalTok{,}
  \AttributeTok{lty =} \DecValTok{2}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Several observations exceed the reference line \(4/n\), but all Cook's
distance values are well below 1. Therefore, there is no strong evidence
of influential observations.

Taken together, the residual diagnostics do not reveal any serious
violation of the standard assumptions underlying ordinary least squares
regression.

\subsubsection{Ill-conditioned design}\label{ill-conditioned-design}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{vif\_manual}\NormalTok{(ols\_model)}
\end{Highlighting}
\end{Shaded}

The variance inflation factors (VIFs) were computed to assess
multicollinearity among the predictors.

The VIF values range from \textbf{1.33} to \textbf{3.24}, with the
largest values observed for

\begin{itemize}
\tightlist
\item
  \texttt{lcp} (3.24),
\item
  \texttt{pgg45} (2.97),
\item
  \texttt{gleason} (2.68), and
\item
  \texttt{lcavol} (2.42).
\end{itemize}

None of the predictors exceeds the commonly used threshold of
\textbf{5}, indicating that severe multicollinearity is not present in
the training design matrix.

This finding is consistent with the correlation analysis presented in
Section 1C. Although several predictor pairs, such as
\texttt{gleason}--\texttt{pgg45} and \texttt{lcavol}--\texttt{lcp},
exhibit moderate pairwise correlations, pairwise correlation alone does
not necessarily imply problematic multicollinearity. The VIF measures
how well each predictor can be explained by \textbf{all remaining
predictors simultaneously}, making it a more appropriate diagnostic for
coefficient instability.

Overall, the VIF results suggest that the correlations among predictors
are not sufficiently strong to produce substantial inflation of the
coefficient variances. Therefore, no clear evidence of an
ill-conditioned design was found, and the OLS estimates provide an
appropriate baseline for comparison with ridge and lasso regression in
the following sections.

\subsection{2B. Ridge}\label{b.-ridge}

\subsubsection{Fitting Ridge}\label{fitting-ridge}

The Ridge model is fitted using \texttt{glmnet} with
\texttt{alpha\ =\ 0} on the training data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ridge\_model }\OtherTok{\textless{}{-}} \FunctionTok{fit\_cv\_glmnet}\NormalTok{(}
\NormalTok{  x\_train,}
\NormalTok{  y\_train,}
  \AttributeTok{alpha =} \DecValTok{0}\NormalTok{,}
  \AttributeTok{foldid =}\NormalTok{ foldid}
\NormalTok{)}

\FunctionTok{plot}\NormalTok{(ridge\_model)}

\FunctionTok{abline}\NormalTok{(}\AttributeTok{v =} \SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{lambda.min),}
       \AttributeTok{col =} \StringTok{"green"}\NormalTok{,}
       \AttributeTok{lty =} \DecValTok{2}\NormalTok{,}
       \AttributeTok{lwd =} \FloatTok{1.5}\NormalTok{)}

\FunctionTok{abline}\NormalTok{(}\AttributeTok{v =} \SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se),}
       \AttributeTok{col =} \StringTok{"blue"}\NormalTok{,}
       \AttributeTok{lty =} \DecValTok{2}\NormalTok{,}
       \AttributeTok{lwd =} \FloatTok{1.5}\NormalTok{)}

\NormalTok{y\_pos }\OtherTok{\textless{}{-}} \FunctionTok{max}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{cvup)}

\FunctionTok{text}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{lambda.min),}
\NormalTok{     y\_pos,}
     \StringTok{"lambda.min"}\NormalTok{,}
     \AttributeTok{pos =} \DecValTok{2}\NormalTok{,}
     \AttributeTok{col =} \StringTok{"green"}\NormalTok{,}
     \AttributeTok{cex =} \FloatTok{0.9}\NormalTok{)}

\FunctionTok{text}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se),}
\NormalTok{     y\_pos,}
     \StringTok{"lambda.1se"}\NormalTok{,}
     \AttributeTok{pos =} \DecValTok{2}\NormalTok{,}
     \AttributeTok{col =} \StringTok{"blue"}\NormalTok{,}
     \AttributeTok{cex =} \FloatTok{0.9}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ASESII_24A02_ProjectExam_SampleSubmission_files/ASESII_24A02_ProjectExam_SampleSubmission_files/figure-latex/ridge-1.pdf}}

The cross-validation curve shows how the prediction error changes with
the penalty parameter. The mean cross-validation error decreases until
reaching its minimum at \textbf{\texttt{lambda.min}}. Around the
minimum, the error changes only slightly, indicating that a range of
penalty values provides similar predictive performance.

Because Ridge regression uses an L2 penalty, every coefficient is
continuously shrunk toward zero as the penalty increases. However, Ridge
does not apply coordinate-wise thresholding, so no coefficient is set
exactly to zero and all eight predictors remain in the model.

\subsubsection{\texorpdfstring{Investigation on \(\lambda_{min}\) and
\(\lambda_{1se}\)}{Investigation on \textbackslash lambda\_\{min\} and \textbackslash lambda\_\{1se\}}}\label{investigation-on-lambda_min-and-lambda_1se}

The optimal penalty values selected by cross-validation are reported
below.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"lambda.min: \%.5f}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{, ridge\_model}\SpecialCharTok{$}\NormalTok{lambda.min))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## lambda.min: 0.28468
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"lambda.1se: \%.5f}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{, ridge\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## lambda.1se: 1.66740
\end{verbatim}

\texttt{lambda.min} is the value of \(\lambda\) that minimizes the mean
cross-validation error. It is selected when predictive accuracy is the
primary objective.

\texttt{lambda.1se} is the largest value of \(\lambda\) whose
cross-validation error is within one standard error of the minimum. It
applies stronger regularization, producing a simpler and more stable
model while usually maintaining similar predictive performance.

The coefficient estimates and corresponding cross-validation error at
\texttt{lambda.min} are shown below.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{min\_id }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{lambda }\SpecialCharTok{==}\NormalTok{ ridge\_model}\SpecialCharTok{$}\NormalTok{lambda.min)}

\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"cvm.min: \%.5f}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{, ridge\_model}\SpecialCharTok{$}\NormalTok{cvm[min\_id]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## cvm.min: 0.63753
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(ridge\_model, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 9 x 1 sparse Matrix of class "dgCMatrix"
##              lambda.min
## (Intercept)  2.54491818
## lcavol       0.45872792
## lweight      0.17492397
## age         -0.11231149
## lbph         0.10203528
## svi          0.23691430
## lcp          0.08238970
## gleason      0.02447306
## pgg45        0.10953781
\end{verbatim}

At \texttt{lambda.min}, the model achieves the lowest cross-validation
error. The coefficients are moderately shrunk compared with the OLS
estimates, while the most important predictors still retain relatively
large coefficients.

The corresponding results for \texttt{lambda.1se} are shown below.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{se1\_id }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{lambda }\SpecialCharTok{==}\NormalTok{ ridge\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se)}

\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"cvm.1se: \%.5f}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{, ridge\_model}\SpecialCharTok{$}\NormalTok{cvm[se1\_id]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## cvm.1se: 0.71834
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(ridge\_model, }\AttributeTok{s =} \StringTok{"lambda.1se"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 9 x 1 sparse Matrix of class "dgCMatrix"
##              lambda.1se
## (Intercept)  2.54491818
## lcavol       0.23622160
## lweight      0.10299748
## age         -0.02250727
## lbph         0.05203722
## svi          0.15871610
## lcp          0.12657524
## gleason      0.04952838
## pgg45        0.08822978
\end{verbatim}

Using the larger penalty \texttt{lambda.1se} shrinks every coefficient
further toward zero than \texttt{lambda.min}. The cross-validation error
increases only slightly from , indicating that a more regularized model
can achieve nearly the same predictive performance.

Unlike Lasso, Ridge regression continuously shrinks the coefficients but
does not set any coefficient exactly to zero. Therefore, every predictor
remains in the fitted model under both tuning parameter choices.

\subsubsection{Coefficient paths}\label{coefficient-paths}

The coefficient paths show how the Ridge coefficients change as the
penalty varies.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{glmnet.fit,}
     \AttributeTok{xvar =} \StringTok{"lambda"}\NormalTok{,}
     \AttributeTok{label =} \ConstantTok{TRUE}\NormalTok{)}

\FunctionTok{title}\NormalTok{(}\StringTok{"Ridge Coefficient Paths"}\NormalTok{, }\AttributeTok{line =} \FloatTok{2.5}\NormalTok{)}

\FunctionTok{abline}\NormalTok{(}\AttributeTok{v =} \SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{lambda.min),}
       \AttributeTok{col =} \StringTok{"green"}\NormalTok{,}
       \AttributeTok{lty =} \DecValTok{2}\NormalTok{,}
       \AttributeTok{lwd =} \FloatTok{1.5}\NormalTok{)}

\FunctionTok{abline}\NormalTok{(}\AttributeTok{v =} \SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se),}
       \AttributeTok{col =} \StringTok{"blue"}\NormalTok{,}
       \AttributeTok{lty =} \DecValTok{2}\NormalTok{,}
       \AttributeTok{lwd =} \FloatTok{1.5}\NormalTok{)}

\FunctionTok{legend}\NormalTok{(}\StringTok{"topleft"}\NormalTok{,}
       \AttributeTok{legend =} \FunctionTok{c}\NormalTok{(}\StringTok{"lambda.min"}\NormalTok{, }\StringTok{"lambda.1se"}\NormalTok{),}
       \AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"green"}\NormalTok{, }\StringTok{"blue"}\NormalTok{),}
       \AttributeTok{lty =} \DecValTok{2}\NormalTok{,}
       \AttributeTok{lwd =} \FloatTok{1.5}\NormalTok{,}
       \AttributeTok{cex =} \FloatTok{0.8}\NormalTok{,}
       \AttributeTok{bg =} \StringTok{"white"}\NormalTok{)}

\NormalTok{predictor\_names }\OtherTok{\textless{}{-}} \FunctionTok{rownames}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{glmnet.fit}\SpecialCharTok{$}\NormalTok{beta)}

\FunctionTok{legend}\NormalTok{(}\StringTok{"topleft"}\NormalTok{,}
       \AttributeTok{inset =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.21}\NormalTok{),}
       \AttributeTok{legend =} \FunctionTok{paste}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(predictor\_names),}
\NormalTok{                      predictor\_names,}
                      \AttributeTok{sep =} \StringTok{" {-} "}\NormalTok{),}
       \AttributeTok{col =} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(predictor\_names),}
       \AttributeTok{lty =} \DecValTok{1}\NormalTok{,}
       \AttributeTok{lwd =} \FloatTok{1.5}\NormalTok{,}
       \AttributeTok{cex =} \FloatTok{0.8}\NormalTok{,}
       \AttributeTok{bg =} \StringTok{"white"}\NormalTok{,}
       \AttributeTok{ncol =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ASESII_24A02_ProjectExam_SampleSubmission_files/ASESII_24A02_ProjectExam_SampleSubmission_files/figure-latex/unnamed-chunk-4-1.pdf}}

As the penalty decreases (moving from left to right), the coefficients
move smoothly away from near zero toward their OLS estimates. Larger
penalties produce stronger shrinkage, whereas smaller penalties allow
the coefficients to approach the unregularized solution.

Unlike Lasso, Ridge continuously shrinks every coefficient and therefore
does not produce exact zero coefficients.

\subsubsection{General Behavior of Correlated Predictors Under Ridge
Regression}\label{general-behavior-of-correlated-predictors-under-ridge-regression}

Ridge regression is particularly effective when predictors are highly
correlated. In ordinary least squares, correlated predictors compete to
explain the same variation in the response, leading to unstable
coefficient estimates with high variance.

Ridge addresses this issue by shrinking the coefficients of correlated
predictors towards each other rather than allowing one predictor to
dominate the others. This reduces the variability of the coefficient
estimates and improves model stability while retaining all predictors in
the model. This behaviour is reflected in the coefficient paths, where
all coefficients are smoothly shrunk towards zero as the penalty
increases.

Unlike Lasso, Ridge regression does not perform variable selection.
Instead, all coefficients are continuously shrunk towards zero, but none
becomes exactly zero.

\paragraph{Examples from the Data}\label{examples-from-the-data}

The effect of Ridge can be seen in several pairs of highly correlated
predictors.

\begin{itemize}
\item
  \textbf{\texttt{lcavol} and \texttt{lcp} (correlation = 0.73):} Under
  OLS, \texttt{lcavol} receives a much larger positive coefficient while
  \texttt{lcp} is assigned a small negative coefficient. Ridge shrinks
  both coefficients, reducing this imbalance and allowing the two
  correlated predictors to share their predictive contribution.
\item
  \textbf{\texttt{pgg45} and \texttt{gleason} (correlation = 0.76):} OLS
  assigns substantially different coefficients to these correlated
  predictors. Ridge shrinks both estimates towards zero, producing more
  stable coefficient estimates while retaining both variables in the
  model.
\end{itemize}

\subsection{2C. Lasso}\label{c.-lasso}

\subsubsection{Fitting Lasso}\label{fitting-lasso}

The lasso model is fitted using \texttt{glmnet} by setting
\texttt{alpha\ =\ 1} on the training data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lasso\_model }\OtherTok{\textless{}{-}} \FunctionTok{fit\_cv\_glmnet}\NormalTok{(}
\NormalTok{  x\_train,}
\NormalTok{  y\_train,}
  \AttributeTok{alpha =} \DecValTok{1}\NormalTok{,}
  \AttributeTok{foldid =}\NormalTok{ foldid}
\NormalTok{)}

\FunctionTok{plot}\NormalTok{(lasso\_model)}

\FunctionTok{abline}\NormalTok{(}\AttributeTok{v =} \SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{lambda.min),}
       \AttributeTok{col =} \StringTok{"green"}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{, }\AttributeTok{lwd =} \FloatTok{1.5}\NormalTok{)}

\FunctionTok{abline}\NormalTok{(}\AttributeTok{v =} \SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se),}
       \AttributeTok{col =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{, }\AttributeTok{lwd =} \FloatTok{1.5}\NormalTok{)}

\NormalTok{y\_pos }\OtherTok{\textless{}{-}} \FunctionTok{max}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{cvup)}

\FunctionTok{text}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{lambda.min), y\_pos,}
     \AttributeTok{labels =} \StringTok{"lambda.min"}\NormalTok{,}
     \AttributeTok{pos =} \DecValTok{2}\NormalTok{, }\AttributeTok{col =} \StringTok{"green"}\NormalTok{, }\AttributeTok{cex =} \FloatTok{0.9}\NormalTok{)}

\FunctionTok{text}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se), y\_pos,}
     \AttributeTok{labels =} \StringTok{"lambda.1se"}\NormalTok{,}
     \AttributeTok{pos =} \DecValTok{2}\NormalTok{, }\AttributeTok{col =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{cex =} \FloatTok{0.9}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ASESII_24A02_ProjectExam_SampleSubmission_files/ASESII_24A02_ProjectExam_SampleSubmission_files/figure-latex/lasso-1.pdf}}

Unlike Ridge regression, Lasso performs both coefficient shrinkage and
variable selection. As the penalty increases, some coefficients are
shrunk exactly to zero, producing a simpler and more interpretable
model. The cross-validation curve identifies the penalty giving the
lowest prediction error (\texttt{lambda.min}) together with the largest
penalty within one standard error (\texttt{lambda.1se}).

\subsubsection{\texorpdfstring{Investigation on \(\lambda_{min}\) and
\(\lambda_{1se}\)}{Investigation on \textbackslash lambda\_\{min\} and \textbackslash lambda\_\{1se\}}}\label{investigation-on-lambda_min-and-lambda_1se-1}

The optimal penalties are

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"lambda.min: \%.5f}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{, lasso\_model}\SpecialCharTok{$}\NormalTok{lambda.min))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## lambda.min: 0.10970
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"lambda.1se: \%.5f}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{, lasso\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## lambda.1se: 0.33502
\end{verbatim}

The corresponding training cross-validation errors are

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{min\_id }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{lambda }\SpecialCharTok{==}\NormalTok{ lasso\_model}\SpecialCharTok{$}\NormalTok{lambda.min)}
\NormalTok{se1\_id }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{lambda }\SpecialCharTok{==}\NormalTok{ lasso\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se)}

\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"cvm.min : \%.5f}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{,}
\NormalTok{            lasso\_model}\SpecialCharTok{$}\NormalTok{cvm[min\_id]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## cvm.min : 0.63210
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"cvm.1se : \%.5f}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{,}
\NormalTok{            lasso\_model}\SpecialCharTok{$}\NormalTok{cvm[se1\_id]))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## cvm.1se : 0.72788
\end{verbatim}

The selected predictors under the two tuning rules are

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"{-}{-}{-} Nonzero coefficients (lambda.min) {-}{-}{-}}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## --- Nonzero coefficients (lambda.min) ---
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{coef\_min }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(lasso\_model, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(coef\_min[coef\_min[, }\DecValTok{1}\NormalTok{] }\SpecialCharTok{!=} \DecValTok{0}\NormalTok{, ]) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)      lcavol     lweight         svi       pgg45 
##  2.54491818  0.60702254  0.10812626  0.17708356  0.02150988
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{{-}{-}{-} Nonzero coefficients (lambda.1se) {-}{-}{-}}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## --- Nonzero coefficients (lambda.1se) ---
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{coef\_1se }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(lasso\_model, }\AttributeTok{s =} \StringTok{"lambda.1se"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(coef\_1se[coef\_1se[, }\DecValTok{1}\NormalTok{] }\SpecialCharTok{!=} \DecValTok{0}\NormalTok{, ])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)      lcavol         svi 
##  2.54491818  0.49176838  0.03845547
\end{verbatim}

\texttt{lambda.min} prioritizes predictive accuracy and therefore
usually keeps more predictors. \texttt{lambda.1se} accepts a small
increase in prediction error in exchange for a sparser and
easier-to-interpret model.

\subsubsection{Coefficient paths}\label{coefficient-paths-1}

The coefficient paths illustrate how predictors enter and leave the
model as the penalty changes.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{glmnet.fit,}
     \AttributeTok{xvar =} \StringTok{"lambda"}\NormalTok{,}
     \AttributeTok{label =} \ConstantTok{TRUE}\NormalTok{)}

\FunctionTok{title}\NormalTok{(}\StringTok{"Lasso Coefficient Paths"}\NormalTok{, }\AttributeTok{line =} \FloatTok{2.5}\NormalTok{)}

\FunctionTok{abline}\NormalTok{(}\AttributeTok{v =} \SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{lambda.min),}
       \AttributeTok{col =} \StringTok{"green"}\NormalTok{,}
       \AttributeTok{lty =} \DecValTok{2}\NormalTok{,}
       \AttributeTok{lwd =} \FloatTok{1.5}\NormalTok{)}

\FunctionTok{abline}\NormalTok{(}\AttributeTok{v =} \SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se),}
       \AttributeTok{col =} \StringTok{"blue"}\NormalTok{,}
       \AttributeTok{lty =} \DecValTok{2}\NormalTok{,}
       \AttributeTok{lwd =} \FloatTok{1.5}\NormalTok{)}

\FunctionTok{legend}\NormalTok{(}\StringTok{"topleft"}\NormalTok{, }
       \AttributeTok{legend =} \FunctionTok{c}\NormalTok{(}\StringTok{"lambda.min"}\NormalTok{, }\StringTok{"lambda.1se"}\NormalTok{), }
       \AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"green"}\NormalTok{, }\StringTok{"blue"}\NormalTok{), }
       \AttributeTok{lty =} \DecValTok{2}\NormalTok{, }
       \AttributeTok{lwd =} \FloatTok{1.5}\NormalTok{, }
       \AttributeTok{cex =} \FloatTok{0.75}\NormalTok{,}
       \AttributeTok{bg =} \StringTok{"white"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ASESII_24A02_ProjectExam_SampleSubmission_files/ASESII_24A02_ProjectExam_SampleSubmission_files/figure-latex/unnamed-chunk-8-1.pdf}}

Unlike Ridge regression, Lasso coefficient paths frequently terminate at
exactly zero. Variables that reach zero are removed from the model,
while only the strongest predictors remain active under larger penalty
values.

\subsubsection{Application-specific
interpretation}\label{application-specific-interpretation}

Lasso identifies the predictors that provide the strongest independent
contribution to explaining \texttt{lpsa} after accounting for the
remaining variables.

At \texttt{lambda.min}, four predictors remain active: \texttt{lcavol},
\texttt{lweight}, \texttt{svi}, and \texttt{pgg45}. Among these,
\texttt{lcavol} has by far the largest coefficient (0.607), indicating
that tumor volume is the strongest predictor of prostate-specific
antigen levels. \texttt{svi} also remains, suggesting that seminal
vesicle invasion contributes additional predictive information beyond
tumor volume. \texttt{lweight} and \texttt{pgg45} have smaller
coefficients but still improve predictive performance enough to be
retained.

At \texttt{lambda.1se}, the stronger penalty removes both
\texttt{lweight} and \texttt{pgg45}, leaving only \texttt{lcavol} and
\texttt{svi}. This indicates that these two variables contain the most
robust independent signal in the data. The cross-validation error
increases only slightly (0.632 to 0.728), while the model is reduced
from four predictors to two, yielding a much simpler and more
interpretable model.

The variables excluded by Lasso (\texttt{age}, \texttt{lbph},
\texttt{lcp}, \texttt{gleason}, \texttt{lweight}, and \texttt{pgg45}
under \texttt{lambda.1se}) are not necessarily unrelated to prostate
cancer. Rather, after accounting for \texttt{lcavol} and \texttt{svi},
their remaining predictive contribution is too small to justify the
additional model complexity. Some of their information is likely shared
with the retained predictors because several clinical measurements are
moderately correlated.

\subsection{2D. Training-based comparison and locked core
model}\label{d.-training-based-comparison-and-locked-core-model}

This section compares the candidate models using only the training data
and cross-validation results. The holdout test set is not used so that
model selection remains unbiased.

\subsubsection{Training-based
comparison}\label{training-based-comparison}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# OLS}
\NormalTok{cv\_ols }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(cv\_mse)}
\NormalTok{coef\_ols }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(ols\_model)}
\NormalTok{norm\_ols }\OtherTok{\textless{}{-}} \FunctionTok{coef\_norm}\NormalTok{(coef\_ols)}
\NormalTok{nz\_ols }\OtherTok{\textless{}{-}} \FunctionTok{nonzero\_slopes}\NormalTok{(coef\_ols)}

\CommentTok{\# Ridge}
\NormalTok{coef\_ridge\_min }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(ridge\_model, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{)}
\NormalTok{coef\_ridge\_1se }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(ridge\_model, }\AttributeTok{s =} \StringTok{"lambda.1se"}\NormalTok{)}

\NormalTok{id\_min }\OtherTok{\textless{}{-}} \FunctionTok{which.min}\NormalTok{(}\FunctionTok{abs}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{lambda }\SpecialCharTok{{-}}\NormalTok{ ridge\_model}\SpecialCharTok{$}\NormalTok{lambda.min))}
\NormalTok{id\_1se }\OtherTok{\textless{}{-}} \FunctionTok{which.min}\NormalTok{(}\FunctionTok{abs}\NormalTok{(ridge\_model}\SpecialCharTok{$}\NormalTok{lambda }\SpecialCharTok{{-}}\NormalTok{ ridge\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se))}

\NormalTok{cv\_ridge\_min }\OtherTok{\textless{}{-}}\NormalTok{ ridge\_model}\SpecialCharTok{$}\NormalTok{cvm[id\_min]}
\NormalTok{cv\_ridge\_1se }\OtherTok{\textless{}{-}}\NormalTok{ ridge\_model}\SpecialCharTok{$}\NormalTok{cvm[id\_1se]}

\NormalTok{norm\_ridge\_min }\OtherTok{\textless{}{-}} \FunctionTok{coef\_norm}\NormalTok{(coef\_ridge\_min)}
\NormalTok{norm\_ridge\_1se }\OtherTok{\textless{}{-}} \FunctionTok{coef\_norm}\NormalTok{(coef\_ridge\_1se)}

\NormalTok{nz\_ridge\_min }\OtherTok{\textless{}{-}} \FunctionTok{nonzero\_slopes}\NormalTok{(coef\_ridge\_min)}
\NormalTok{nz\_ridge\_1se }\OtherTok{\textless{}{-}} \FunctionTok{nonzero\_slopes}\NormalTok{(coef\_ridge\_1se)}

\CommentTok{\# Lasso}
\NormalTok{coef\_lasso\_min }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(lasso\_model, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{)}
\NormalTok{coef\_lasso\_1se }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(lasso\_model, }\AttributeTok{s =} \StringTok{"lambda.1se"}\NormalTok{)}

\NormalTok{id\_min }\OtherTok{\textless{}{-}} \FunctionTok{which.min}\NormalTok{(}\FunctionTok{abs}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{lambda }\SpecialCharTok{{-}}\NormalTok{ lasso\_model}\SpecialCharTok{$}\NormalTok{lambda.min))}
\NormalTok{id\_1se }\OtherTok{\textless{}{-}} \FunctionTok{which.min}\NormalTok{(}\FunctionTok{abs}\NormalTok{(lasso\_model}\SpecialCharTok{$}\NormalTok{lambda }\SpecialCharTok{{-}}\NormalTok{ lasso\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se))}

\NormalTok{cv\_lasso\_min }\OtherTok{\textless{}{-}}\NormalTok{ lasso\_model}\SpecialCharTok{$}\NormalTok{cvm[id\_min]}
\NormalTok{cv\_lasso\_1se }\OtherTok{\textless{}{-}}\NormalTok{ lasso\_model}\SpecialCharTok{$}\NormalTok{cvm[id\_1se]}

\NormalTok{norm\_lasso\_min }\OtherTok{\textless{}{-}} \FunctionTok{coef\_norm}\NormalTok{(coef\_lasso\_min)}
\NormalTok{norm\_lasso\_1se }\OtherTok{\textless{}{-}} \FunctionTok{coef\_norm}\NormalTok{(coef\_lasso\_1se)}

\NormalTok{nz\_lasso\_min }\OtherTok{\textless{}{-}} \FunctionTok{nonzero\_slopes}\NormalTok{(coef\_lasso\_min)}
\NormalTok{nz\_lasso\_1se }\OtherTok{\textless{}{-}} \FunctionTok{nonzero\_slopes}\NormalTok{(coef\_lasso\_1se)}

\NormalTok{comparison\_table }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Model =} \FunctionTok{c}\NormalTok{(}
    \StringTok{"OLS"}\NormalTok{,}
    \StringTok{"Ridge"}\NormalTok{,}
    \StringTok{"Ridge"}\NormalTok{,}
    \StringTok{"Lasso"}\NormalTok{,}
    \StringTok{"Lasso"}
\NormalTok{  ),}
  \AttributeTok{Tuning =} \FunctionTok{c}\NormalTok{(}
    \StringTok{"None"}\NormalTok{,}
    \StringTok{"lambda.min"}\NormalTok{,}
    \StringTok{"lambda.1se"}\NormalTok{,}
    \StringTok{"lambda.min"}\NormalTok{,}
    \StringTok{"lambda.1se"}
\NormalTok{  ),}
  \AttributeTok{CV\_MSE =} \FunctionTok{c}\NormalTok{(}
\NormalTok{    cv\_ols,}
\NormalTok{    cv\_ridge\_min,}
\NormalTok{    cv\_ridge\_1se,}
\NormalTok{    cv\_lasso\_min,}
\NormalTok{    cv\_lasso\_1se}
\NormalTok{  ),}
  \AttributeTok{Coefficient\_Norm =} \FunctionTok{c}\NormalTok{(}
\NormalTok{    norm\_ols,}
\NormalTok{    norm\_ridge\_min,}
\NormalTok{    norm\_ridge\_1se,}
\NormalTok{    norm\_lasso\_min,}
\NormalTok{    norm\_lasso\_1se}
\NormalTok{  ),}
  \AttributeTok{Nonzero\_Slopes =} \FunctionTok{c}\NormalTok{(}
\NormalTok{    nz\_ols,}
\NormalTok{    nz\_ridge\_min,}
\NormalTok{    nz\_ridge\_1se,}
\NormalTok{    nz\_lasso\_min,}
\NormalTok{    nz\_lasso\_1se}
\NormalTok{  )}
\NormalTok{)}

\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(comparison\_table, }\AttributeTok{digits =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}llrrr@{}}
\toprule\noalign{}
Model & Tuning & CV\_MSE & Coefficient\_Norm & Nonzero\_Slopes \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
OLS & None & 0.6947 & 0.8154 & 8 \\
Ridge & lambda.min & 0.6375 & 0.5827 & 8 \\
Ridge & lambda.1se & 0.7183 & 0.3480 & 8 \\
Lasso & lambda.min & 0.6321 & 0.6419 & 4 \\
Lasso & lambda.1se & 0.7279 & 0.4933 & 2 \\
\end{longtable}
}

Regularization improves predictive performance over OLS, with both Ridge
(\texttt{lambda.min}) and Lasso (\texttt{lambda.min}) achieving lower
cross-validation errors. Ridge shrinks the coefficients but retains all
eight predictors, whereas Lasso also performs variable selection. Lasso
(\texttt{lambda.min}) achieves the lowest cross-validation error while
retaining only four predictors, providing the best balance between
prediction accuracy and model simplicity.

\subsubsection{Core model nominated before holdout
evaluation}\label{core-model-nominated-before-holdout-evaluation}

Based on the training results, \textbf{Lasso with \texttt{lambda.min}}
is selected as the core candidate. It achieves the lowest
cross-validation error while reducing the model from eight predictors to
four. Although Ridge (\texttt{lambda.min}) has similar predictive
performance, it retains all predictors and is therefore less
interpretable.

\subsubsection{\texorpdfstring{Why \texttt{lambda.min} and
\texttt{lambda.1se} answer different decision
questions}{Why lambda.min and lambda.1se answer different decision questions}}\label{why-lambda.min-and-lambda.1se-answer-different-decision-questions}

\texttt{lambda.min} prioritizes predictive performance by minimizing the
cross-validation error. In contrast, \texttt{lambda.1se} selects a
larger penalty to obtain a simpler and more stable model while accepting
a small increase in prediction error.

\subsubsection{Predictive performance versus
interpretability}\label{predictive-performance-versus-interpretability}

Predictive performance is assessed by the cross-validation error,
whereas interpretability depends on model simplicity. In this analysis,
Lasso (\texttt{lambda.min}) achieves the lowest prediction error while
retaining only four predictors, making it the preferred model before the
final holdout evaluation.

\subsection{2E. Perturbation or stability
check}\label{e.-perturbation-or-stability-check}

This stability check investigates how Ridge and Lasso respond to severe
multicollinearity by duplicating a predictor with a small amount of
random noise. The experiment uses only the training data.

\subsubsection{Prediction before running the
check}\label{prediction-before-running-the-check}

Before running the perturbation, we expect Ridge to distribute the
coefficient between the original and duplicated predictors because the
ridge penalty encourages correlated predictors to share their effects.
In contrast, Lasso is expected to retain only one of the two predictors
while shrinking the other coefficient to zero.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Duplicate a strong predictor with small random noise}
\NormalTok{target\_idx }\OtherTok{\textless{}{-}} \DecValTok{1}
\NormalTok{target\_name }\OtherTok{\textless{}{-}} \FunctionTok{colnames}\NormalTok{(x\_train)[target\_idx]}

\NormalTok{duplicate\_var }\OtherTok{\textless{}{-}}\NormalTok{ x\_train[, target\_idx] }\SpecialCharTok{+}
  \FunctionTok{rnorm}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(x\_train), }\AttributeTok{sd =} \FloatTok{0.01}\NormalTok{)}

\NormalTok{x\_train\_pert }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}
\NormalTok{  x\_train,}
  \AttributeTok{duplicate\_var =}\NormalTok{ duplicate\_var}
\NormalTok{)}

\CommentTok{\# Refit Ridge and Lasso using the perturbed data}
\NormalTok{ridge\_pert }\OtherTok{\textless{}{-}} \FunctionTok{fit\_cv\_glmnet}\NormalTok{(}
\NormalTok{  x\_train\_pert,}
\NormalTok{  y\_train,}
  \AttributeTok{alpha =} \DecValTok{0}\NormalTok{,}
  \AttributeTok{foldid =}\NormalTok{ foldid}
\NormalTok{)}

\NormalTok{lasso\_pert }\OtherTok{\textless{}{-}} \FunctionTok{fit\_cv\_glmnet}\NormalTok{(}
\NormalTok{  x\_train\_pert,}
\NormalTok{  y\_train,}
  \AttributeTok{alpha =} \DecValTok{1}\NormalTok{,}
  \AttributeTok{foldid =}\NormalTok{ foldid}
\NormalTok{)}

\NormalTok{ridge\_coef }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(ridge\_pert, }\AttributeTok{s =} \StringTok{"lambda.1se"}\NormalTok{)}
\NormalTok{lasso\_coef }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(lasso\_pert, }\AttributeTok{s =} \StringTok{"lambda.1se"}\NormalTok{)}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Ridge:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Ridge:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(ridge\_coef[}\FunctionTok{c}\NormalTok{(target\_name, }\StringTok{"duplicate\_var"}\NormalTok{), , }\AttributeTok{drop =} \ConstantTok{FALSE}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 2 x 1 sparse Matrix of class "dgCMatrix"
##               lambda.1se
## lcavol         0.1560755
## duplicate_var  0.1559359
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Lasso:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Lasso:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(lasso\_coef[}\FunctionTok{c}\NormalTok{(target\_name, }\StringTok{"duplicate\_var"}\NormalTok{), , }\AttributeTok{drop =} \ConstantTok{FALSE}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 2 x 1 sparse Matrix of class "dgCMatrix"
##               lambda.1se
## lcavol         0.4917684
## duplicate_var  .
\end{verbatim}

\subsubsection{Observed result and
explanation}\label{observed-result-and-explanation}

The perturbation confirms the expected behaviour of the two
regularization methods.

Ridge assigns almost identical coefficients to the original predictor
(\texttt{lcavol} = 0.1560) and its duplicate (0.1561), indicating that
the effect is shared between highly correlated predictors. This
behaviour improves coefficient stability in the presence of
multicollinearity.

In contrast, Lasso retains the original predictor (\texttt{lcavol} =
0.4918) while shrinking the duplicated predictor exactly to zero. This
demonstrates that Lasso performs variable selection by choosing one
representative predictor and discarding redundant correlated variables.

Overall, the perturbation illustrates the different mechanisms of Ridge
and Lasso. Ridge stabilizes coefficient estimates by sharing information
across correlated predictors, whereas Lasso produces a sparse and more
interpretable model by selecting only one predictor from a correlated
group.

\section{Problem 3. Mathematical
mechanisms}\label{problem-3.-mathematical-mechanisms}

\subsection{3A. Ridge and conditioning}\label{a.-ridge-and-conditioning}

\emph{Write the ridge derivation. Define dimensions and explain
uniqueness.}

Let
\(X \in \mathbb{R}^{n \times p}, y \in \mathbb{R}^n, b \in \mathbb{R}^p\)
and define \[G = \frac{1}{n} X^\top X, \quad
z = \frac{1}{n} X^\top y\] consequently,
\(G \in \mathbb{R}^{p \times p}\) and \(z \in \mathbb{R}^p\).

From the objective function
\[Q_\lambda(b) = \frac{1}{2n}\|y - Xb\|_2^2 + \frac{\lambda}{2}\|b\|_2^2\]

We expand Ridge objective function \begin{align}
  Q_\lambda (b) &= \frac{1}{2n} \|y - X b\|_2^2 + \frac{\lambda}{2} \|b\|_2^2, \quad (\lambda > 0) \\
  &= \frac{1}{2n} (y - X b)^\top (y - X b) + \frac{\lambda}{2} b^\top b \\
  &= \frac{1}{2n} (y^\top y - y^\top X b - b^\top X^\top y + b^\top X^\top X b) + \frac{\lambda}{2} b^\top b \\
  &= \frac{1}{2n} (y^\top y - 2 y^\top X b + b^\top X^\top X b) + \frac{\lambda}{2} b^\top b \\
\end{align}

We take the gradient with respect to \(b\) and substitute \begin{align}
  \nabla_b Q_\lambda (b) &= 0 - \frac{1}{n} y^\top X + \frac{1}{n} X^\top X b + \lambda b \\
  &= - z + G b + \lambda b
\end{align}

Set
\(\nabla_b Q_\lambda (b) = 0 \Leftrightarrow (G + \lambda I_p) b = z\)
which is the \(\textbf{normal equation}\).

Because \(G = \frac{1}{n}X^\top X\) is a positive semi-definite Gram
matrix, all its eigenvalues are \(\ge 0\). Adding a penalty
\(\lambda > 0\) along the diagonal (i.e., \(\lambda I_p\)) shifts all
eigenvalues up by \(\lambda\). Thus, the matrix \((G + \lambda I_p)\) is
strictly positive definite (all eigenvalues \(\ge \lambda > 0\)), making
it full rank and invertible. This guarantees a unique minimizer

\[\hat{b}_\lambda^{\text{ridge}} = (G + \lambda I_p)^{-1} z\]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Use x\_train and the fitted ridge lambda.min.}
\CommentTok{\# safe\_condition\_numbers(x\_train, lambda = ...)}

\NormalTok{condition\_numbers }\OtherTok{\textless{}{-}} \FunctionTok{safe\_condition\_numbers}\NormalTok{(x\_train, ridge\_model}\SpecialCharTok{$}\NormalTok{lambda.min)}
\NormalTok{kappa\_G }\OtherTok{\textless{}{-}}\NormalTok{ condition\_numbers[}\StringTok{"gram"}\NormalTok{]}
\NormalTok{kappa\_ridge }\OtherTok{\textless{}{-}}\NormalTok{ condition\_numbers[}\StringTok{"ridge"}\NormalTok{]}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Condition number of G (kappa\_G):"}\NormalTok{, kappa\_G, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Condition number of Ridge (kappa\_ridge):"}\NormalTok{, kappa\_ridge, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{Numerical interpretation}\label{numerical-interpretation}

The OLS estimator is

\[\hat b=(X^\top X)^{-1}X^\top y,\]

so its numerical stability depends on the Gram matrix

\[G=X^\top X.\]

When predictors are highly correlated, the columns of \(X\) become
nearly linearly dependent, making

\[\det(G)\approx0.\]

Equivalently,

\[G=Q\Lambda Q^\top,
\qquad
\Lambda=\operatorname{diag}(\mu_1,\ldots,\mu_p),\]

contains one or more very small eigenvalues. Since

\[G^{-1}
=
Q\Lambda^{-1}Q^\top,
\qquad
\Lambda^{-1}
=
\operatorname{diag}
\left(
\frac1{\mu_1},
\ldots,
\frac1{\mu_p}
\right),\]

a small eigenvalue

\[\mu_{\min}\approx0\]

produces a very large reciprocal

\[\frac{1}{\mu_{\min}}
\rightarrow
\infty.\]

Therefore, the inverse \((X^\top X)^{-1}\) amplifies small perturbations
in the data, making the coefficient estimate

\[\hat b=(X^\top X)^{-1}X^\top y\]

highly sensitive to sampling variation and numerical error.

This instability is summarized by the spectral condition number

\[\kappa_2(G)
=
\frac{\mu_{\max}}
{\mu_{\min}},\]

where a large value indicates an ill-conditioned matrix.

Ridge replaces \(G\) by

\[G+\lambda I,\]

which shifts every eigenvalue by

\[\mu_i
\longrightarrow
\mu_i+\lambda.\]

Hence,

\[\kappa_2(G+\lambda I)
=
\frac{\mu_{\max}+\lambda}
{\mu_{\min}+\lambda}.\]

Since the smallest eigenvalue increases the most in relative terms, the
condition number decreases, making the matrix inversion and coefficient
estimates substantially more stable.

\subsubsection{Geometric interpretation}\label{geometric-interpretation}

The least-squares objective is

\[RSS(b)=\|y-Xb\|^2,\]

whose Hessian is

\[\nabla^2RSS(b)=2X^\top X=2G.\]

Thus, the eigenvalues of \(G\) determine the curvature of the loss
surface. When one eigenvalue is much smaller than the others, the
curvature in that direction is very weak, producing long, narrow
elliptical contours. Along this nearly flat valley, many coefficient
vectors produce almost identical values of \(RSS(b)\), so a small
perturbation in the data can move the optimum a large distance, leading
to unstable coefficients.

Ridge adds the penalty

\[\lambda\|b\|_2^2,\]

whose Hessian is

\[2\lambda I.\]

Therefore, the penalized Hessian becomes

\[2(G+\lambda I),\]

increasing the curvature in every direction, especially those
corresponding to the smallest eigenvalues. The elongated ellipses become
more circular, the optimum is better localized, and the coefficient
estimates become more stable while retaining all predictors.

\subsection{3B. Lasso optimality and soft
thresholding}\label{b.-lasso-optimality-and-soft-thresholding}

\emph{Derive the zero/nonzero optimality conditions and the
orthonormal-design formula.}

Let
\(X \in \mathbb{R}^{n \times p}, y \in \mathbb{R}^n, b \in \mathbb{R}^p\)
and define \[G = \frac{1}{n} X^\top X = I_p, \quad
z = \frac{1}{n} X^\top y\] consequently,
\(G \in \mathbb{R}^{p \times p}\) and \(z \in \mathbb{R}^p\).

The objective function
\[R_\lambda (b) = \frac{1}{2n} \|y - X b\|_2^2 + \lambda \|b\|_1, \quad \|b\|_1 = \sum_{j=1}^p |b_j|, \lambda > 0\]

We expand Lasso objective function \[\begin{aligned}
R_\lambda (b) &= \frac{1}{2n} \|y - X b\|_2^2 + \lambda \|b\|_1 \\
              &= \frac{1}{2n} (y - X b)^\top (y - X b) + \lambda \sum_{j=1}^p |b_j| \\
              &= \frac{1}{2n} (y^\top y - y^\top X b - b^\top X^\top y + b^\top X^\top X b) + \lambda \sum_{j=1}^p |b_j|
\end{aligned}\]

The term \(y^\top X b\) is is a scalar, therefore
\((y^\top X b)^\top = b^\top X^\top (y^\top)^\top = b^\top X^\top y\).

Then the objective becomes \[\begin{aligned}
R_\lambda (b) &= \frac{1}{2n} y^\top y - \frac{1}{n} b^\top X^\top y + \frac{1}{2n} b^\top X^\top X b + \lambda \sum_{j=1}^p |b_j| \\
              &= \frac{1}{2n} y^\top y - b^\top z + \frac{1}{2} b^\top b + \lambda \sum_{j=1}^p |b_j| \\
              &= \frac{1}{2n} y^\top y + \sum_{j=1}^p \left( - b_j z_j + \frac{1}{2} b_j^2 + \lambda |b_j| \right)
\end{aligned}\]

The term \(\frac{1}{2n} y^\top y\) is a constant with respect to the
variable \(b\). , leaving a sum of \(p\) independent 1-dimensional
optimization problems.

Consider a fixed \(j\), and let
\(l_j (t) = \frac{1}{2} t^2 - t z_j + \lambda |t|\), for
\(t \in \mathbb{R}\). We analyze this in three cases because \(|t|\) is
\emph{non-differentiable} at \(t=0\).

\begin{itemize}
\item
  \textbf{Case 1:} If \(t > 0\), then \(|t| = t\) and
  \(l_j (t) = \frac{1}{2} t^2 - t z_j + \lambda t\). Thus,
  \(l_j' (t) = t - z_j + \lambda\).
  \[ l_j' (t) = 0 \iff t = z_j - \lambda \quad (1) \] Moreover, since we
  assumed \(t > 0\), equation \((1)\) is a valid minimum if and only if
  \(z_j > \lambda\).
\item
  \textbf{Case 2:} If \(t < 0\), then \(|t| = - t\) and
  \(l_j (t) = \frac{1}{2} t^2 - t z_j - \lambda t\). Thus,
  \(l_j' (t) = t - z_j - \lambda\).
  \[ l_j' (t) = 0 \iff t = z_j + \lambda \quad (2) \] Moreover, since we
  assumed \(t < 0\), equation \((2)\) is a valid minimum if and only if
  \(z_j < -\lambda\).
\item
  \textbf{Case 3:} If \(|z_j| \le \lambda\), there is no valid solution
  where the derivative equals zero (neither Case 1 nor Case 2). Because
  the function is strictly convex, the global minimum must exist, which
  means it is trapped exactly at the non-differentiable corner:
  \(t = 0\). We verify that \(t = 0\) minimizes \(l_j (t)\) (3).
\end{itemize}

For any \(t \in \mathbb{R}\) \[\begin{aligned}
l_j (t) - l_j (0) &= \frac{1}{2} t^2 - t z_j + \lambda |t| \\
                  &\ge \frac{1}{2} t^2 - |t| |z_j| + \lambda |t| \quad (-t z_j \ge -|t| |z_j|) \\
                  &\ge \frac{1}{2} t^2 - |t| (|z_j| - \lambda) \\
                  &\ge 0 \quad (|z_j| - \lambda \le 0)
\end{aligned}\] Therefore, \(l_j (t) \ge l_j (0)\) for all
\(t \in \mathbb{R}\), proving \(t=0\) is the global minimum for this
range.

Combining these cases yields the soft-thresholding estimator for
\(\hat{b}_j\): \[\hat{b}_j = \begin{cases}
  z_j - \lambda & \text{if } z_j > \lambda, \\
  0             & \text{if } |z_j| \le \lambda, \\
  z_j + \lambda & \text{if } z_j < -\lambda
\end{cases}\]

The uniqueness is guaranteed because the objective function is strictly
convex. Under the orthogonal design, the variables are perfectly
independent, forming a strictly convex ``bowl'' shape. Even with the
sharp point added by the \(L_1\) penalty, the strict convexity
mathematically ensures there is exactly one absolute global minimum.

\textbf{Soft-thresholding operator under orthonormal design} Assume that
\(\frac{1}{n} X^T X = I_p\). Let \(z = \frac{1}{n} X^T y\). Then the
Lasso minimizer of \(R_\lambda (b)\) is \emph{unique} and has
coordinates
\[\hat{b}_j = S_\lambda (z_j), \quad \text{where the soft-thresholding function is } S_\lambda (z) = \text{sgn}(z) (|z| - \lambda)_+\]
where \((u)_+ = \max(u, 0)\).

\textbf{Why lasso can produce exact zeros while ridge generally does
not.} Under \(\frac{1}{n} X^T X = I_p\), we can compare the closed-form
estimators

\begin{itemize}
\tightlist
\item
  \textbf{Ridge:} \(\hat{b}_j^{\text{Ridge}} = (1 +  \lambda)^{-1} z_j\)
  (proportional shrinkage). It divides the coefficient by a constant.
  The coefficients get extremely small, but they never become zero. The
  optimality condition means \(b_j\) only equals exactly zero if \(z_j\)
  is exactly zero (which is highly improbable with real data).
\item
  \textbf{Lasso:}
  \(\hat{b}_j^{\text{Lasso}} = \text{sgn}(z_j) (|z_j| - \lambda)_+\)
  (absolute shrinkage). It subtracts a constant from the magnitude. If a
  coefficient is originally small, the penalty forces it to exactly
  zero. Case 3 shows that Lasso maps a whole range of values to exactly
  zero, creating sparsity. This gives Lasso its \textbf{feature
  selection} capability.
\end{itemize}

\subsection{3C. Connect algebra to
evidence}\label{c.-connect-algebra-to-evidence}

The ridge results in Section 2B provide direct evidence for the
conditioning analysis in Section 3A. At the selected tuning parameter,

\[\lambda_{\min}=0.28468,\]

the condition number decreased from

\[\kappa_2(G)=16.97\]

to

\[\kappa_2(G+\lambda I)=7.49,\]

representing a reduction of more than 50\%. This confirms that adding
\(\lambda I\) increased the smallest eigenvalues of the Gram matrix,
making the linear system substantially better conditioned.

The improved conditioning is reflected in the fitted ridge coefficients.
Compared with OLS, the coefficient of \texttt{lcavol} was shrunk from
\textbf{0.6740} to \textbf{0.4587}, while the coefficient of the
correlated predictor \texttt{lcp} changed from \textbf{−0.0924} to
\textbf{0.0824}. Rather than allowing these correlated predictors to
compete for unstable coefficients, Ridge shrinks them simultaneously and
distributes their shared contribution more evenly. This behaviour is
also visible in the smooth coefficient paths, where all coefficients
move continuously towards zero as the penalty increases, but none
becomes exactly zero.

Overall, the numerical evidence supports the theoretical result of
Section 3A: shifting the eigenvalues by \(\lambda\) improves the
conditioning of the Gram matrix, leading to more stable coefficient
estimates while retaining all predictors.

\section{Problem 4. Elastic net and a neural-feature
bridge}\label{problem-4.-elastic-net-and-a-neural-feature-bridge}

\subsection{4A. Research question and source
map}\label{a.-research-question-and-source-map}

\textbf{Research Question:}

\emph{How does the methodological mechanism of} \(L_2\) regularization -
which stabilizes models by damping parameter variance along
low-eigenvalue directions - diverge from algorithmic weight decay when
training deep neural networks with adaptive gradient optimizers?

\textbf{Context \& Methodological Bridge}

In classical linear models and neural networks trained with standard
Stochastic Gradient Descent (SGD), adding an \(L_2\) penalty to the loss
function and applying algorithmic weight decay are mathematically
identical operations. When minimizing a loss function
\(\mathcal{L}(w) + \frac{\lambda}{2} \Vert{}w\Vert{}_2^2\), the
derivative of the penalty introduces a \(+\lambda w\) term to the
gradient. Inside the standard SGD update rule, this factors into a decay
multiplier:
\(w_{t+1} = (1 - \alpha\lambda)w_t - \alpha \nabla \mathcal{L}(w_t)\).

However, in modern deep neural networks, models are primarily trained
using adaptive optimizers like Adam. Loshchilov and Hutter (2019)
demonstrated that placing the \(L_2\) penalty inside the loss function
causes it to be divided by Adam's adaptive gradient scaling factor. This
neutralizes the penalty for weights with large gradients and
hyper-inflates it for sparse gradients. To restore the classical,
eigenvalue-damping properties of \(L_2\) regularization in deep
learning, weight decay must be mathematically decoupled from the loss
gradient (AdamW).

\textbf{Source Map}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Claim
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Exact Source and Locator
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
What the Source Establishes
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
What it does not establish
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Proposition 1:} For SGD, weight decay is equivalent to \(L_2\)
regularization after learning-rate rescaling. & Loshchilov \& Hutter
(2019), Section 2, Proposition 1 & Proves the mathematical equivalence
between SGD weight decay and \(L_2\) regularization. & Does not extend
this equivalence to adaptive optimizers. \\
\textbf{Proposition 2:} For adaptive optimizers, weight decay is not
equivalent to \(L_2\) regularization. & Loshchilov \& Hutter (2019),
Section 2, Proposition 2 & Proves adaptive gradient scaling changes the
effect of \(L_2\) regularization, motivating AdamW. & Does not prove
AdamW always performs better. \\
\textbf{Proposition 3:} With a fixed preconditioner, weight decay
corresponds to a weighted \(L_2\) regularizer. & Loshchilov \& Hutter
(2019), Section 2, Proposition 3 & Derives the equivalent weighted
regularizer under fixed preconditioning. & Does not apply directly to
practical Adam with a changing preconditioner. \\
\textbf{Empirical:} AdamW improves generalization and simplifies
hyperparameter tuning. & Loshchilov \& Hutter (2019), Sections 4.2--4.4,
Figures 2--4 & Shows AdamW achieves lower test error and easier
hyperparameter tuning than Adam. & Does not guarantee improvements
across all models or datasets. \\
\textbf{Theoretical:} Weight decay selects the minimum-norm solution,
improving generalization in linear networks. & Krogh \& Hertz (1991),
Section 3, Eqs. (6)--(10) & Proves weight decay removes irrelevant
weight components and favors the minimum-norm solution. & Does not prove
the result for general non-linear networks. \\
\textbf{Theoretical:} Weight decay reduces overfitting to noisy targets.
& Krogh \& Hertz (1991), Section 4, Eqs. (12)--(17) & Derives an optimal
weight decay for noisy linear models and shows reduced generalization
error. & Does not show the same optimum applies to deep neural
networks. \\
\textbf{Theoretical:} Weight decay can be extended to non-linear
networks via local linearization. & Krogh \& Hertz (1991), Section 5 &
Argues that weight decay favors lower-complexity solutions in non-linear
networks. & Does not provide a rigorous proof for arbitrary non-linear
networks. \\
\textbf{Empirical:} Weight decay lowers generalization and prediction
error on NetTalk. & Krogh \& Hertz (1991), Section 6, Figure 2 &
Demonstrates improved performance with weight decay on the NetTalk
benchmark. & Does not establish the same gains for modern architectures
such as CNNs or Transformers. \\
\end{longtable}
}

\textbf{References}

\begin{itemize}
\item
  Krogh, A., \& Hertz, J. A. (1992). A simple weight decay can improve
  generalization. In \emph{Advances in Neural Information Processing
  Systems} (Vol. 4, pp.~950-957).
\item
  Loshchilov, I., \& Hutter, F. (2019). Decoupling weight decay from
  gradient-based optimizers. In \emph{International Conference on
  Learning Representations (ICLR)}.
\end{itemize}

\subsection{4B. Elastic net on original
predictors}\label{b.-elastic-net-on-original-predictors}

Elastic Net combines the \(L_1\) penalty of Lasso and the \(L_2\)
penalty of Ridge. The objective is to determine whether a mixture of the
two penalties can achieve a better balance between prediction accuracy,
coefficient stability, and model sparsity than either method alone.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{alpha\_grid }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{0.10}\NormalTok{, }\FloatTok{0.25}\NormalTok{, }\FloatTok{0.50}\NormalTok{, }\FloatTok{0.75}\NormalTok{, }\FloatTok{0.90}\NormalTok{)}

\NormalTok{enet\_models }\OtherTok{\textless{}{-}} \FunctionTok{vector}\NormalTok{(}\StringTok{"list"}\NormalTok{, }\FunctionTok{length}\NormalTok{(alpha\_grid))}

\NormalTok{enet\_summary }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{alpha =}\NormalTok{ alpha\_grid,}
  \AttributeTok{lambda.min =} \ConstantTok{NA\_real\_}\NormalTok{,}
  \AttributeTok{lambda.1se =} \ConstantTok{NA\_real\_}\NormalTok{,}
  \AttributeTok{cvm.min =} \ConstantTok{NA\_real\_}\NormalTok{,}
  \AttributeTok{cvm.1se =} \ConstantTok{NA\_real\_}\NormalTok{,}
  \AttributeTok{nonzero.min =} \ConstantTok{NA\_integer\_}\NormalTok{,}
  \AttributeTok{nonzero.1se =} \ConstantTok{NA\_integer\_}
\NormalTok{)}

\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \FunctionTok{seq\_along}\NormalTok{(alpha\_grid))\{}

\NormalTok{  fit }\OtherTok{\textless{}{-}} \FunctionTok{fit\_cv\_glmnet}\NormalTok{(}
    \AttributeTok{x =}\NormalTok{ x\_train,}
    \AttributeTok{y =}\NormalTok{ y\_train,}
    \AttributeTok{alpha =}\NormalTok{ alpha\_grid[i],}
    \AttributeTok{foldid =}\NormalTok{ foldid}
\NormalTok{  )}

\NormalTok{  enet\_models[[i]] }\OtherTok{\textless{}{-}}\NormalTok{ fit}

\NormalTok{  id\_min }\OtherTok{\textless{}{-}} \FunctionTok{which.min}\NormalTok{(}\FunctionTok{abs}\NormalTok{(fit}\SpecialCharTok{$}\NormalTok{lambda }\SpecialCharTok{{-}}\NormalTok{ fit}\SpecialCharTok{$}\NormalTok{lambda.min))}
\NormalTok{  id\_1se }\OtherTok{\textless{}{-}} \FunctionTok{which.min}\NormalTok{(}\FunctionTok{abs}\NormalTok{(fit}\SpecialCharTok{$}\NormalTok{lambda }\SpecialCharTok{{-}}\NormalTok{ fit}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se))}

\NormalTok{  enet\_summary}\SpecialCharTok{$}\NormalTok{lambda.min[i] }\OtherTok{\textless{}{-}}\NormalTok{ fit}\SpecialCharTok{$}\NormalTok{lambda.min}
\NormalTok{  enet\_summary}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se[i] }\OtherTok{\textless{}{-}}\NormalTok{ fit}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se}

\NormalTok{  enet\_summary}\SpecialCharTok{$}\NormalTok{cvm.min[i] }\OtherTok{\textless{}{-}}\NormalTok{ fit}\SpecialCharTok{$}\NormalTok{cvm[id\_min]}
\NormalTok{  enet\_summary}\SpecialCharTok{$}\NormalTok{cvm}\FloatTok{.1}\NormalTok{se[i] }\OtherTok{\textless{}{-}}\NormalTok{ fit}\SpecialCharTok{$}\NormalTok{cvm[id\_1se]}

\NormalTok{  enet\_summary}\SpecialCharTok{$}\NormalTok{nonzero.min[i] }\OtherTok{\textless{}{-}}
    \FunctionTok{count\_nonzero}\NormalTok{(fit, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{)}

\NormalTok{  enet\_summary}\SpecialCharTok{$}\NormalTok{nonzero}\FloatTok{.1}\NormalTok{se[i] }\OtherTok{\textless{}{-}}
    \FunctionTok{count\_nonzero}\NormalTok{(fit, }\AttributeTok{s =} \StringTok{"lambda.1se"}\NormalTok{)}
\NormalTok{\}}

\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(enet\_summary, }\AttributeTok{digits =} \DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0882}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1618}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1618}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1176}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1176}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1765}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1765}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
alpha
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
lambda.min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
lambda.1se
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
cvm.min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
cvm.1se
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
nonzero.min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
nonzero.1se
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
0.10 & 0.2056 & 0.9996 & 0.6363 & 0.7127 & 7 & 7 \\
0.25 & 0.1309 & 0.6366 & 0.6346 & 0.7034 & 7 & 5 \\
0.50 & 0.1144 & 0.4208 & 0.6335 & 0.7026 & 6 & 5 \\
0.75 & 0.1106 & 0.3709 & 0.6331 & 0.7159 & 6 & 2 \\
0.90 & 0.1111 & 0.3392 & 0.6323 & 0.7171 & 4 & 2 \\
\end{longtable}
}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{best\_id }\OtherTok{\textless{}{-}} \FunctionTok{which.min}\NormalTok{(enet\_summary}\SpecialCharTok{$}\NormalTok{cvm.min)}

\NormalTok{best\_alpha }\OtherTok{\textless{}{-}}\NormalTok{ enet\_summary}\SpecialCharTok{$}\NormalTok{alpha[best\_id]}
\NormalTok{best\_model }\OtherTok{\textless{}{-}}\NormalTok{ enet\_models[[best\_id]]}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Selected alpha :"}\NormalTok{, best\_alpha, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Selected alpha : 0.9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Selected lambda:"}\NormalTok{, best\_model}\SpecialCharTok{$}\NormalTok{lambda.min, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Selected lambda: 0.1110642
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Minimum CV MSE :"}\NormalTok{, }\FunctionTok{min}\NormalTok{(best\_model}\SpecialCharTok{$}\NormalTok{cvm), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Minimum CV MSE : 0.6323101
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(best\_model, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 9 x 1 sparse Matrix of class "dgCMatrix"
##             lambda.min
## (Intercept) 2.54491818
## lcavol      0.60062327
## lweight     0.11674208
## age         .         
## lbph        .         
## svi         0.18406394
## lcp         .         
## gleason     .         
## pgg45       0.03091681
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}
\NormalTok{  best\_model}\SpecialCharTok{$}\NormalTok{glmnet.fit,}
  \AttributeTok{xvar =} \StringTok{"lambda"}\NormalTok{,}
  \AttributeTok{label =} \ConstantTok{TRUE}
\NormalTok{)}

\FunctionTok{title}\NormalTok{(}
  \FunctionTok{paste}\NormalTok{(}\StringTok{"Elastic Net Paths (alpha ="}\NormalTok{, best\_alpha, }\StringTok{")"}\NormalTok{),}
  \AttributeTok{line =} \FloatTok{2.5}
\NormalTok{)}

\FunctionTok{abline}\NormalTok{(}
  \AttributeTok{v =} \SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(best\_model}\SpecialCharTok{$}\NormalTok{lambda.min),}
  \AttributeTok{col =} \StringTok{"green"}\NormalTok{,}
  \AttributeTok{lty =} \DecValTok{2}\NormalTok{,}
  \AttributeTok{lwd =} \FloatTok{1.5}
\NormalTok{)}

\FunctionTok{abline}\NormalTok{(}
  \AttributeTok{v =} \SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(best\_model}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se),}
  \AttributeTok{col =} \StringTok{"blue"}\NormalTok{,}
  \AttributeTok{lty =} \DecValTok{2}\NormalTok{,}
  \AttributeTok{lwd =} \FloatTok{1.5}
\NormalTok{)}

\FunctionTok{legend}\NormalTok{(}
  \StringTok{"topleft"}\NormalTok{,}
  \AttributeTok{legend =} \FunctionTok{c}\NormalTok{(}\StringTok{"lambda.min"}\NormalTok{, }\StringTok{"lambda.1se"}\NormalTok{),}
  \AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"green"}\NormalTok{, }\StringTok{"blue"}\NormalTok{),}
  \AttributeTok{lty =} \DecValTok{2}\NormalTok{,}
  \AttributeTok{lwd =} \FloatTok{1.5}\NormalTok{,}
  \AttributeTok{bg =} \StringTok{"white"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{ASESII_24A02_ProjectExam_SampleSubmission_files/ASESII_24A02_ProjectExam_SampleSubmission_files/figure-latex/original-elastic-net-1.pdf}}

\subsubsection{Selection rule}\label{selection-rule}

For each candidate value of \(\alpha\), an Elastic Net model was fitted
using the common five-fold cross-validation assignment
(\texttt{foldid}). For each model, the tuning parameter \(\lambda\) was
selected by \texttt{lambda.min}, the value that minimized the mean
cross-validation mean squared error. The final value of \(\alpha\) was
then chosen as the one producing the smallest minimum cross-validation
error across the candidate grid.

The results are summarized above. As \(\alpha\) increases from 0.10 to
0.90, the minimum cross-validation error decreases gradually from
\textbf{0.6363} to \textbf{0.6323}, while the number of active
predictors at \texttt{lambda.min} decreases from \textbf{7} to
\textbf{4}. Consequently, \(\alpha=0.90\) was selected because it
achieved the smallest cross-validation error (\textbf{CV MSE = 0.6323})
with the sparsest model among the candidate values.

At the selected tuning parameters,

\begin{itemize}
\tightlist
\item
  \(\alpha = 0.90\),
\item
  \(\lambda_{\min}=0.1111\),
\end{itemize}

the fitted model retained four predictors:

\begin{itemize}
\tightlist
\item
  \texttt{lcavol},
\item
  \texttt{lweight},
\item
  \texttt{svi},
\item
  \texttt{pgg45}.
\end{itemize}

The remaining four predictors (\texttt{age}, \texttt{lbph},
\texttt{lcp}, and \texttt{gleason}) were shrunk exactly to zero.

\subsubsection{Relationship with Ridge and Lasso in Problem
2}\label{relationship-with-ridge-and-lasso-in-problem-2}

Elastic Net combines the \(L_1\) penalty of Lasso with the \(L_2\)
penalty of Ridge, producing a solution between the two methods.

In Problem 2, Ridge retained all \textbf{eight predictors} because the
\(L_2\) penalty shrinks coefficients continuously without setting them
to zero, whereas Lasso selected a sparse model by shrinking several
coefficients exactly to zero.

For the prostate dataset, the selected Elastic Net model uses
\(\alpha=0.90\) with \(\lambda_{\min}=0.1111\) and achieves the lowest
cross-validation error (\textbf{CV MSE = 0.6323}). At this solution,
only four predictors (\texttt{lcavol}, \texttt{lweight}, \texttt{svi},
and \texttt{pgg45}) remain active, while the remaining four coefficients
are shrunk exactly to zero.

Thus, the fitted model is much closer to Lasso in terms of variable
selection, but the remaining \textbf{10\%} \(L_2\) penalty
(\(1-\alpha=0.10\)) still provides additional coefficient stabilization
for correlated predictors. Consequently, Elastic Net combines the
sparsity of Lasso with part of the stability and grouping behaviour of
Ridge.

\subsection{4C. Fixed ReLU features}\label{c.-fixed-relu-features}

Using the standardized training predictors, we constructed \(M = 200\)
fixed random ReLU features of the form

\[h_m(x)=\max\{a_m^\top x+c_m,0\},
\qquad m=1,\ldots,M,\]

where

\[a_m\sim N\left(0,\frac1pI_p\right),\]

and

\[c_m\sim N(0,0.5^2).\]

The random weights and offsets were generated once using the declared
seed and then applied unchanged to both the training and test sets.
Hidden features with zero variance in the training data were removed
using training information only.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(seeds}\SpecialCharTok{$}\NormalTok{features)}

\NormalTok{relu }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(z) }\FunctionTok{pmax}\NormalTok{(z, }\DecValTok{0}\NormalTok{)}

\NormalTok{M }\OtherTok{\textless{}{-}} \DecValTok{200}\DataTypeTok{L}
\NormalTok{p }\OtherTok{\textless{}{-}} \FunctionTok{ncol}\NormalTok{(x\_train)}

\CommentTok{\# Generate random hidden{-}layer parameters}
\NormalTok{A\_matrix }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}
  \FunctionTok{rnorm}\NormalTok{(}
\NormalTok{    p }\SpecialCharTok{*}\NormalTok{ M,}
    \AttributeTok{mean =} \DecValTok{0}\NormalTok{,}
    \AttributeTok{sd =} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{/}\NormalTok{ p)}
\NormalTok{  ),}
  \AttributeTok{nrow =}\NormalTok{ p,}
  \AttributeTok{ncol =}\NormalTok{ M}
\NormalTok{)}

\NormalTok{c\_bias }\OtherTok{\textless{}{-}} \FunctionTok{rnorm}\NormalTok{(}
\NormalTok{  M,}
  \AttributeTok{mean =} \DecValTok{0}\NormalTok{,}
  \AttributeTok{sd =} \FloatTok{0.5}
\NormalTok{)}

\CommentTok{\# Construct ReLU features}
\NormalTok{H\_train\_raw }\OtherTok{\textless{}{-}} \FunctionTok{relu}\NormalTok{(}
  \FunctionTok{sweep}\NormalTok{(}
\NormalTok{    x\_train }\SpecialCharTok{\%*\%}\NormalTok{ A\_matrix,}
    \DecValTok{2}\NormalTok{,}
\NormalTok{    c\_bias,}
    \StringTok{"+"}
\NormalTok{  )}
\NormalTok{)}

\NormalTok{H\_test\_raw }\OtherTok{\textless{}{-}} \FunctionTok{relu}\NormalTok{(}
  \FunctionTok{sweep}\NormalTok{(}
\NormalTok{    x\_test }\SpecialCharTok{\%*\%}\NormalTok{ A\_matrix,}
    \DecValTok{2}\NormalTok{,}
\NormalTok{    c\_bias,}
    \StringTok{"+"}
\NormalTok{  )}
\NormalTok{)}

\CommentTok{\# Remove constant hidden features using training only}
\NormalTok{keep\_hidden }\OtherTok{\textless{}{-}} \FunctionTok{apply}\NormalTok{(}
\NormalTok{  H\_train\_raw,}
  \DecValTok{2}\NormalTok{,}
\NormalTok{  sd}
\NormalTok{) }\SpecialCharTok{\textgreater{}} \DecValTok{0}

\NormalTok{H\_train\_raw }\OtherTok{\textless{}{-}}\NormalTok{ H\_train\_raw[}
\NormalTok{  ,}
\NormalTok{  keep\_hidden,}
\NormalTok{  drop }\OtherTok{=} \ConstantTok{FALSE}
\NormalTok{]}

\NormalTok{H\_test\_raw }\OtherTok{\textless{}{-}}\NormalTok{ H\_test\_raw[}
\NormalTok{  ,}
\NormalTok{  keep\_hidden,}
\NormalTok{  drop }\OtherTok{=} \ConstantTok{FALSE}
\NormalTok{]}

\FunctionTok{cat}\NormalTok{(}
  \StringTok{"Hidden features retained:"}\NormalTok{,}
  \FunctionTok{ncol}\NormalTok{(H\_train\_raw),}
  \StringTok{"out of"}\NormalTok{,}
\NormalTok{  M,}
  \StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Hidden features retained: 198 out of 200
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Standardize hidden features using training statistics}
\NormalTok{h\_prep }\OtherTok{\textless{}{-}} \FunctionTok{fit\_scaler}\NormalTok{(H\_train\_raw)}

\NormalTok{H\_train }\OtherTok{\textless{}{-}} \FunctionTok{apply\_scaler}\NormalTok{(}
\NormalTok{  H\_train\_raw,}
\NormalTok{  h\_prep}
\NormalTok{)}

\NormalTok{H\_test }\OtherTok{\textless{}{-}} \FunctionTok{apply\_scaler}\NormalTok{(}
\NormalTok{  H\_test\_raw,}
\NormalTok{  h\_prep}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Ridge, lasso, and elastic net were fitted on the fixed ReLU feature
matrix using the shared five-fold cross-validation assignment. For
elastic net, the mixing parameter \(\alpha\) was selected from the same
candidate grid as in Part 4B.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ridge\_relu }\OtherTok{\textless{}{-}} \FunctionTok{fit\_cv\_glmnet}\NormalTok{(}
\NormalTok{  H\_train,}
\NormalTok{  y\_train,}
  \AttributeTok{alpha =} \DecValTok{0}\NormalTok{,}
  \AttributeTok{foldid =}\NormalTok{ foldid}
\NormalTok{)}

\NormalTok{lasso\_relu }\OtherTok{\textless{}{-}} \FunctionTok{fit\_cv\_glmnet}\NormalTok{(}
\NormalTok{  H\_train,}
\NormalTok{  y\_train,}
  \AttributeTok{alpha =} \DecValTok{1}\NormalTok{,}
  \AttributeTok{foldid =}\NormalTok{ foldid}
\NormalTok{)}

\NormalTok{alpha\_grid }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \FloatTok{0.10}\NormalTok{,}
  \FloatTok{0.25}\NormalTok{,}
  \FloatTok{0.50}\NormalTok{,}
  \FloatTok{0.75}\NormalTok{,}
  \FloatTok{0.90}
\NormalTok{)}

\NormalTok{enet\_models }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(}
\NormalTok{  alpha\_grid,}
  \ControlFlowTok{function}\NormalTok{(alpha)}
    \FunctionTok{fit\_cv\_glmnet}\NormalTok{(}
\NormalTok{      H\_train,}
\NormalTok{      y\_train,}
      \AttributeTok{alpha =}\NormalTok{ alpha,}
      \AttributeTok{foldid =}\NormalTok{ foldid}
\NormalTok{    )}
\NormalTok{)}

\NormalTok{cv\_errors }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(}
\NormalTok{  enet\_models,}
  \ControlFlowTok{function}\NormalTok{(model) }\FunctionTok{min}\NormalTok{(model}\SpecialCharTok{$}\NormalTok{cvm)}
\NormalTok{)}

\NormalTok{best\_id }\OtherTok{\textless{}{-}} \FunctionTok{which.min}\NormalTok{(cv\_errors)}

\NormalTok{best\_alpha\_relu }\OtherTok{\textless{}{-}}\NormalTok{ alpha\_grid[best\_id]}

\NormalTok{enet\_relu }\OtherTok{\textless{}{-}}\NormalTok{ enet\_models[[best\_id]]}
\end{Highlighting}
\end{Shaded}

The selected tuning values, training cross-validation errors, and
numbers of active hidden features are summarized below.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{relu\_summary }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}

  \AttributeTok{Model =} \FunctionTok{c}\NormalTok{(}
    \StringTok{"Ridge"}\NormalTok{,}
    \StringTok{"Lasso"}\NormalTok{,}
    \StringTok{"Elastic net"}
\NormalTok{  ),}

  \AttributeTok{Alpha =} \FunctionTok{c}\NormalTok{(}
    \DecValTok{0}\NormalTok{,}
    \DecValTok{1}\NormalTok{,}
\NormalTok{    best\_alpha\_relu}
\NormalTok{  ),}

  \AttributeTok{Lambda =} \FunctionTok{c}\NormalTok{(}
\NormalTok{    ridge\_relu}\SpecialCharTok{$}\NormalTok{lambda.min,}
\NormalTok{    lasso\_relu}\SpecialCharTok{$}\NormalTok{lambda.min,}
\NormalTok{    enet\_relu}\SpecialCharTok{$}\NormalTok{lambda.min}
\NormalTok{  ),}

  \AttributeTok{CV\_Error =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{min}\NormalTok{(ridge\_relu}\SpecialCharTok{$}\NormalTok{cvm),}
    \FunctionTok{min}\NormalTok{(lasso\_relu}\SpecialCharTok{$}\NormalTok{cvm),}
    \FunctionTok{min}\NormalTok{(enet\_relu}\SpecialCharTok{$}\NormalTok{cvm)}
\NormalTok{  ),}

  \AttributeTok{Active\_Hidden =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{count\_nonzero}\NormalTok{(ridge\_relu),}
    \FunctionTok{count\_nonzero}\NormalTok{(lasso\_relu),}
    \FunctionTok{count\_nonzero}\NormalTok{(enet\_relu)}
\NormalTok{  )}
\NormalTok{)}

\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
\NormalTok{  relu\_summary,}
  \AttributeTok{digits =} \DecValTok{4}\NormalTok{,}
  \AttributeTok{caption =} \StringTok{"Cross{-}validation results on the fixed ReLU features."}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrrr@{}}
\caption{Cross-validation results on the fixed ReLU
features.}\tabularnewline
\toprule\noalign{}
Model & Alpha & Lambda & CV\_Error & Active\_Hidden \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Model & Alpha & Lambda & CV\_Error & Active\_Hidden \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Ridge & 0.0 & 7.9035 & 0.6980 & 198 \\
Lasso & 1.0 & 0.1414 & 0.7719 & 11 \\
Elastic net & 0.1 & 1.0208 & 0.7323 & 46 \\
\end{longtable}

\subsubsection{Fixed and learned
parameters}\label{fixed-and-learned-parameters}

The hidden-layer weight vectors \(a_m\) and offsets \(c_m\) were fixed
after being generated once from their specified normal distributions.
These random feature parameters were reused unchanged for both the
training and test sets and were not estimated from the data.

The learned quantities were the regression coefficients associated with
the hidden features and the intercept. Cross-validation selected the
regularization parameter \(\lambda\) for ridge and lasso, and selected
both the mixing parameter \(\alpha\) and the regularization parameter
\(\lambda\) for elastic net.

Among the three models, ridge achieved the smallest training
cross-validation error (0.6980) but retained almost every hidden feature
(198), producing the least sparse model. Lasso selected only 11 active
hidden features, giving the sparsest representation but also the largest
cross-validation error (0.7719). Elastic net selected \(\alpha=0.10\),
retained 46 hidden features, and achieved an intermediate
cross-validation error (0.7323), providing a compromise between
prediction accuracy and sparsity.
------------------------------------------------------------------ \#\#
4D. Locked analysis and final holdout evaluation

\subsubsection{Locked analysis
declaration}\label{locked-analysis-declaration}

Before inspecting the holdout responses (\texttt{y\_test}), the analysis
was locked as follows.

\begin{itemize}
\tightlist
\item
  Predictors were standardized using the training statistics only.
\item
  The same five-fold cross-validation assignment was used for all
  regularized models.
\item
  Fixed ReLU features were generated once using 240406 with
  \texttt{M\ =\ 200} hidden features and reused unchanged.
\item
  Candidate models:

  \begin{itemize}
  \tightlist
  \item
    OLS
  \item
    Ridge (\texttt{lambda.min})
  \item
    Lasso (\texttt{lambda.min})
  \item
    Elastic Net (\texttt{alpha\ =\ 0.90}, \texttt{lambda.min})
  \item
    Ridge + ReLU (\texttt{lambda.min})
  \item
    Lasso + ReLU (\texttt{lambda.min})
  \item
    Elastic Net + ReLU (\texttt{alpha\ =\ 0.10}, \texttt{lambda.min})
  \end{itemize}
\item
  The nominated deployment model was \textbf{Elastic Net on the original
  predictors}.
\item
  Holdout performance was evaluated using RMSE and MAE.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-} Original{-}feature models {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\NormalTok{pred\_ols }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(}
\NormalTok{  ols\_model,}
  \AttributeTok{newdata =} \FunctionTok{as.data.frame}\NormalTok{(x\_test)}
\NormalTok{)}

\NormalTok{pred\_ridge }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}
  \FunctionTok{predict}\NormalTok{(ridge\_model, }\AttributeTok{newx =}\NormalTok{ x\_test, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{)}
\NormalTok{)}

\NormalTok{pred\_lasso }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}
  \FunctionTok{predict}\NormalTok{(lasso\_model, }\AttributeTok{newx =}\NormalTok{ x\_test, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{)}
\NormalTok{)}

\NormalTok{pred\_enet }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}
  \FunctionTok{predict}\NormalTok{(best\_model, }\AttributeTok{newx =}\NormalTok{ x\_test, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{)}
\NormalTok{)}

\DocumentationTok{\#\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-} ReLU{-}feature models {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\NormalTok{pred\_ridge\_relu }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}
  \FunctionTok{predict}\NormalTok{(ridge\_relu, }\AttributeTok{newx =}\NormalTok{ H\_test, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{)}
\NormalTok{)}

\NormalTok{pred\_lasso\_relu }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}
  \FunctionTok{predict}\NormalTok{(lasso\_relu, }\AttributeTok{newx =}\NormalTok{ H\_test, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{)}
\NormalTok{)}

\NormalTok{pred\_enet\_relu }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}
  \FunctionTok{predict}\NormalTok{(enet\_relu, }\AttributeTok{newx =}\NormalTok{ H\_test, }\AttributeTok{s =} \StringTok{"lambda.min"}\NormalTok{)}
\NormalTok{)}

\NormalTok{holdout\_results }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}
  \AttributeTok{Model =} \FunctionTok{c}\NormalTok{(}
    \StringTok{"OLS"}\NormalTok{,}
    \StringTok{"Ridge"}\NormalTok{,}
    \StringTok{"Lasso"}\NormalTok{,}
    \StringTok{"Elastic Net"}\NormalTok{,}
    \StringTok{"Ridge + ReLU"}\NormalTok{,}
    \StringTok{"Lasso + ReLU"}\NormalTok{,}
    \StringTok{"Elastic Net + ReLU"}
\NormalTok{  ),}
  \AttributeTok{RMSE =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_ols)[}\StringTok{"RMSE"}\NormalTok{],}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_ridge)[}\StringTok{"RMSE"}\NormalTok{],}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_lasso)[}\StringTok{"RMSE"}\NormalTok{],}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_enet)[}\StringTok{"RMSE"}\NormalTok{],}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_ridge\_relu)[}\StringTok{"RMSE"}\NormalTok{],}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_lasso\_relu)[}\StringTok{"RMSE"}\NormalTok{],}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_enet\_relu)[}\StringTok{"RMSE"}\NormalTok{]}
\NormalTok{  ),}
  \AttributeTok{MAE =} \FunctionTok{c}\NormalTok{(}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_ols)[}\StringTok{"MAE"}\NormalTok{],}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_ridge)[}\StringTok{"MAE"}\NormalTok{],}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_lasso)[}\StringTok{"MAE"}\NormalTok{],}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_enet)[}\StringTok{"MAE"}\NormalTok{],}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_ridge\_relu)[}\StringTok{"MAE"}\NormalTok{],}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_lasso\_relu)[}\StringTok{"MAE"}\NormalTok{],}
    \FunctionTok{score\_regression}\NormalTok{(y\_test, pred\_enet\_relu)[}\StringTok{"MAE"}\NormalTok{]}
\NormalTok{  )}
\NormalTok{)}

\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{kable}\NormalTok{(}
\NormalTok{  holdout\_results,}
  \AttributeTok{digits =} \DecValTok{4}\NormalTok{,}
  \AttributeTok{caption =} \StringTok{"Holdout performance of all locked candidate models."}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrr@{}}
\caption{Holdout performance of all locked candidate
models.}\tabularnewline
\toprule\noalign{}
Model & RMSE & MAE \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Model & RMSE & MAE \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
OLS & 0.7296 & 0.6137 \\
Ridge & 0.7654 & 0.6230 \\
Lasso & 0.7743 & 0.6167 \\
Elastic Net & 0.7676 & 0.6137 \\
Ridge + ReLU & 0.7660 & 0.6238 \\
Lasso + ReLU & 0.7787 & 0.6391 \\
Elastic Net + ReLU & 0.7563 & 0.6134 \\
\end{longtable}

\subsubsection{Holdout evaluation}\label{holdout-evaluation}

The holdout evaluation was performed only once after the analysis had
been locked. No hyperparameters were retuned, no predictors were
replaced, and no random features were regenerated after inspecting the
holdout responses.

OLS achieved the smallest holdout RMSE (0.7296), while Elastic Net with
fixed ReLU features achieved the smallest MAE (0.6134). Among the
regularized models, Elastic Net with fixed ReLU features also produced
the smallest RMSE (0.7563), improving on Elastic Net fitted to the
original predictors (0.7676).

The holdout evidence does not fully support the training-based decision.
Elastic Net on the original predictors was nominated using
cross-validation, but OLS performed best on this particular holdout
sample. Since the holdout set contains only 20 observations, this
difference is reasonably attributed to sampling variability. Following
the locked-analysis protocol, the nominated deployment model is not
changed after viewing the holdout results.

\subsection{4E. Deep-learning connection and
limitations}\label{e.-deep-learning-connection-and-limitations}

\subsection{4E. Discussion}\label{e.-discussion}

\subsubsection{\texorpdfstring{1. \(L_2\) penalty versus weight
decay}{1. L\_2 penalty versus weight decay}}\label{l_2-penalty-versus-weight-decay}

In this experiment, only the \textbf{output weights} are optimized while
the hidden-layer parameters remain fixed. Applying an \(L_2\) penalty to
the output weights is therefore equivalent to \textbf{ridge regression},
which shrinks the learned coefficients to reduce overfitting. However,
in fully trainable neural networks using adaptive optimizers such as
Adam, adding an \(L_2\) penalty to the loss is generally \textbf{not
equivalent} to weight decay because adaptive gradient scaling changes
the effect of the regularization term. AdamW resolves this by decoupling
weight decay from the gradient update
(\citeproc{ref-loshchilov2019adamw}{Loshchilov and Hutter 2019}).

\subsubsection{2. Zero output weights do not create sparse hidden
weights}\label{zero-output-weights-do-not-create-sparse-hidden-weights}

Each hidden feature is generated from fixed random input-to-hidden
weights and remains unchanged throughout training. If an output weight
becomes zero, the corresponding hidden feature no longer contributes to
the prediction. However, the input-to-hidden weights that generate this
feature remain unchanged because they are never optimized. Therefore,
sparsity occurs only in the \textbf{output layer}, not in the hidden
layer or the network structure.

\subsubsection{3. Dropout is not the same as
pruning}\label{dropout-is-not-the-same-as-pruning}

Dropout randomly masks a subset of hidden activations during each
training iteration, with a new mask sampled for every mini-batch. During
inference, all neurons remain active. In contrast, pruning permanently
removes weights or neurons from the network. Therefore, dropout is a
temporary regularization method, whereas pruning permanently changes the
model architecture.

\subsubsection{4. Conclusions cannot be generalized to fully trained
deep
networks}\label{conclusions-cannot-be-generalized-to-fully-trained-deep-networks}

This experiment uses a \textbf{frozen hidden layer}, where the random
hidden weights and biases are generated once and remain fixed. Only the
output weights are learned. Consequently, the experiment evaluates
regularization on \textbf{fixed random features} rather than on
representations learned jointly with the hidden layers. The results
therefore cannot be directly generalized to fully trained deep neural
networks, where all layers are optimized together
(\citeproc{ref-krogh1992weightdecay}{Krogh and Hertz 1992}).

\subsubsection{Limitations}\label{limitations}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Sensitivity to the random-feature seed.} The hidden features
  are generated from a single random initialization. Different seeds may
  produce different feature representations and model performance, so
  the results may depend on the chosen seed.
\item
  \textbf{Frozen hidden representation.} Since only the output layer is
  trained, the experiment does not evaluate how regularization affects
  feature learning in end-to-end trained neural networks.
\item
  \textbf{Limited experimental setting.} The conclusions are based on
  one hidden-layer architecture with 200 ReLU features and a single
  dataset. They may not generalize to deeper architectures, different
  activation functions, or other datasets.
\end{enumerate}

\section*{Abstract}\label{abstract-1}
\addcontentsline{toc}{section}{Abstract}

This study investigates log prostate-specific antigen (\texttt{lpsa})
prediction in 97 prostatectomy patients using clinical covariates. To
mitigate multicollinearity and prevent target leakage, we implement an
immutable 80/20 train/test partition with training-only preprocessing.
We compare Ordinary Least Squares (OLS) against regularized linear
models (Ridge, Lasso, Elastic Net) and a non-linear Random ReLU feature
representation (\(M=200\)). Mathematical derivations confirm that
\(L_2\) regularization stabilizes ill-conditioned Gram matrices by
upwardly shifting eigenvalues, reducing the condition number by over
50\% (\(\kappa\) dropped from 16.97 to 7.49). Empirical five-fold
cross-validation identifies Lasso (\texttt{lambda.min}) and Elastic Net
as superior predictors over baseline OLS and static non-linear
projections. For clinical deployment, we nominate the Elastic Net model
on original predictors, which optimizes out-of-sample generalization
while collaboratively shrinking correlated biomarkers. We emphasize that
regularized coefficients represent conditional predictive slopes rather
than causal biological mechanisms.

\section{Problem 5. Report quality and
reproducibility}\label{problem-5.-report-quality-and-reproducibility}

\subsection{5A. Reproduction record}\label{a.-reproduction-record}

To independently reproduce the results, figures, and evaluation tables
in this report, execute the following steps from a clean R session:

\subsubsection{1. Folder Layout and
Setup}\label{folder-layout-and-setup}

Ensure the working directory contains the R Markdown file, the
bibliography file, and the raw CSV datasets inside a local
\texttt{data/} subdirectory:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ASESII\_24A02\_Project/}
\NormalTok{├── ASESII\_24A02\_ProjectExam\_Ridge\_Lasso\_ProblemStatement.pdf}
\NormalTok{├── data/}
\NormalTok{    └── prostate.csv}
\NormalTok{├── README.md     }
\NormalTok{└── templates/}
\NormalTok{    ├── ASESII\_24A02\_ProjectExam\_SampleSubmission.Rmd        }
\NormalTok{    ├── ASESII\_24A02\_ProjectExam\_SampleSubmission.pdf}
\NormalTok{    ├── Group06\_AI\_Log.csv       }
\NormalTok{    └── references.bib        }
\end{Highlighting}
\end{Shaded}

\subsubsection{2. Execution Commands}\label{execution-commands}

Open a clean R session (in RStudio via
\texttt{Session\ -\textgreater{}\ Restart\ R}), clear the workspace, and
render the document from the console using relative paths:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Clear workspace and verify clean session}
\FunctionTok{rm}\NormalTok{(}\AttributeTok{list =} \FunctionTok{ls}\NormalTok{())}
\FunctionTok{gc}\NormalTok{()}

\CommentTok{\# Verify required packages are installed}
\NormalTok{required\_pkgs }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"tidyverse"}\NormalTok{, }\StringTok{"glmnet"}\NormalTok{, }\StringTok{"broom"}\NormalTok{, }\StringTok{"knitr"}\NormalTok{, }\StringTok{"rmarkdown"}\NormalTok{)}
\FunctionTok{invisible}\NormalTok{(}\FunctionTok{lapply}\NormalTok{(required\_pkgs, }\ControlFlowTok{function}\NormalTok{(pkg) \{}
  \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(pkg, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{)) }\FunctionTok{install.packages}\NormalTok{(pkg)}
\NormalTok{\}))}

\CommentTok{\# Render the report to HTML/PDF using relative paths}
\NormalTok{rmarkdown}\SpecialCharTok{::}\FunctionTok{render}\NormalTok{(}\StringTok{"templates/ASESII\_24A02\_ProjectExam\_SampleSubmission.Rmd"}\NormalTok{, }\AttributeTok{output\_format =} \StringTok{"all"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{3. Holdout Quarantine
Audit}\label{holdout-quarantine-audit}

\begin{itemize}
\tightlist
\item
  \textbf{Where holdout responses first enter:} The holdout response
  vector \texttt{y\_test} is partitioned during the initial data split
  in \textbf{Section 1B (\texttt{split-and-scale} chunk)}, but it is
  strictly quarantined throughout all exploratory data analysis (Section
  1C), baseline OLS modeling (Section 2A), regularized model tuning
  (Sections 2B--2C), and non-linear feature engineering (Section 4C).
\item
  \textbf{Point of first computation:} \texttt{y\_test} enters
  mathematical computation for the absolute first and only time in
  \textbf{Section 4D (\texttt{final-holdout-evaluation} chunk)}, where
  it is evaluated against fixed candidate predictions to compute
  out-of-sample Root Mean Squared Error (RMSE) and Mean Absolute Error
  (MAE).
\end{itemize}

\subsection{5B. Recommendation and
limitations}\label{b.-recommendation-and-limitations}

\subsubsection{1. Final deployment
recommendation}\label{final-deployment-recommendation}

Although the ordinary least squares (OLS) model achieved the lowest
holdout RMSE on this particular train/test split, we recommend the
\textbf{Elastic Net model} (using the tuning parameters selected by
cross-validation) for practical deployment.

This recommendation reflects the model selection procedure adopted in
this study. Hyperparameters were selected exclusively by
cross-validation on the training data, while the holdout set was
reserved for a single unbiased final evaluation. Because the prostate
cancer predictors exhibit moderate multicollinearity, Elastic Net
provides a good balance between predictive performance, coefficient
stability, and model complexity by combining Ridge shrinkage with Lasso
variable selection. Although OLS performed slightly better on this
particular holdout split, Elastic Net is expected to provide more robust
performance across future samples.

\subsubsection{2. Prediction versus
interpretation}\label{prediction-versus-interpretation}

The preferred model depends on the objective of the analysis.

\begin{itemize}
\item
  \textbf{Prediction.} For predicting future patient outcomes, the
  selected Elastic Net model provides a good compromise between
  predictive accuracy, coefficient stability, and model complexity. Its
  regression coefficients should be interpreted only as conditional
  associations within the fitted model and \textbf{not as evidence of
  causal effects}.
\item
  \textbf{Interpretation.} If the primary objective is identifying a
  compact subset of important predictors rather than maximizing
  predictive accuracy, a more strongly regularized Lasso model (for
  example, using \texttt{lambda.1se}) may be preferred. This produces a
  simpler and more interpretable model while accepting a small reduction
  in predictive performance.
\end{itemize}

\subsubsection{3. Study limitations}\label{study-limitations}

\begin{itemize}
\item
  \textbf{Small sample size.} The analysis is based on only 97
  observations (77 training and 20 holdout samples). Consequently,
  performance estimates are subject to sampling variability, and
  different data splits may produce different model rankings.
\item
  \textbf{Limited external validity.} The dataset represents a
  historical clinical cohort from a single institution. External
  validation on more recent and diverse patient populations would be
  required before clinical deployment.
\item
  \textbf{Single holdout evaluation.} Model performance was evaluated
  using one fixed holdout partition. Although this preserves an unbiased
  final assessment, it does not quantify the variability of the reported
  test errors across repeated train/test splits.
\item
  \textbf{Fixed random feature mapping.} The ReLU feature expansion in
  Section 4 used randomly generated hidden features without
  backpropagation. Therefore, the results evaluate fixed random feature
  representations rather than fully trained neural networks.
\end{itemize}

\subsection{5C. AI verification record}\label{c.-ai-verification-record}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2329}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3014}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2329}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2329}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
AI-assisted item
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Verification procedure
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Evidence
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Final decision
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Ridge regression derivation (Section 3A)} & Re-derived the
penalized least squares objective using matrix calculus and verified
each differentiation step against standard references. & Confirmed the
normal equation \((X^\top X + \lambda I_p)\hat{\beta} = X^\top y\) and
the resulting closed-form Ridge estimator. & \textbf{Accepted with minor
revision:} Improved notation and expanded intermediate algebraic steps
for clarity. \\
\textbf{Lasso soft-thresholding derivation (Section 3B)} & Verified the
coordinate-wise optimization using subgradient conditions under an
orthonormal design matrix. & Confirmed that the solution is the
soft-thresholding operator and that the derivation is valid only under
the stated orthonormal assumption. & \textbf{Accepted:} Mathematical
derivation was consistent after explicitly stating the required
assumptions. \\
\textbf{Manual VIF helper function} & Compared the custom implementation
with the output of \texttt{car::vif()} using the baseline OLS model. &
Both methods produced identical variance inflation factors up to
numerical precision. & \textbf{Accepted:} The custom implementation was
retained to avoid introducing an additional package dependency. \\
\textbf{Discussion of weight decay and adaptive optimization (Section
4A)} & Checked theoretical claims against the original literature on L2
regularization and decoupled weight decay. & Confirmed that adaptive
optimizers such as Adam make L2 regularization and weight decay no
longer equivalent, consistent with Loshchilov and Hutter (2019). &
\textbf{Accepted with revision:} Removed unsupported claims and
restricted the discussion to statements directly supported by the cited
references. \\
\end{longtable}
}

\section*{Preflight and session
information}\label{preflight-and-session-information}
\addcontentsline{toc}{section}{Preflight and session information}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Audit: Verify every critical pipeline object exists before generating final deliverables}
\NormalTok{required\_objects }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
  \StringTok{"train\_id"}\NormalTok{, }\StringTok{"test\_id"}\NormalTok{, }\StringTok{"x\_train"}\NormalTok{, }\StringTok{"x\_test"}\NormalTok{, }\StringTok{"y\_train"}\NormalTok{, }\StringTok{"y\_test"}\NormalTok{, }
  \StringTok{"foldid"}\NormalTok{, }\StringTok{"ols\_model"}\NormalTok{, }\StringTok{"ridge\_model"}\NormalTok{, }\StringTok{"lasso\_model"}
\NormalTok{)}

\NormalTok{missing\_objects }\OtherTok{\textless{}{-}} \FunctionTok{setdiff}\NormalTok{(required\_objects, }\FunctionTok{ls}\NormalTok{())}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(missing\_objects) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
  \FunctionTok{stop}\NormalTok{(}
    \StringTok{"Preflight Check Failed. Missing required pipeline objects: "}\NormalTok{,}
    \FunctionTok{paste}\NormalTok{(missing\_objects, }\AttributeTok{collapse =} \StringTok{", "}\NormalTok{)}
\NormalTok{  )}
\NormalTok{\}}

\CommentTok{\# Safeguard: Verify absolute zero row overlap between train and test partitions}
\FunctionTok{stopifnot}\NormalTok{(}\StringTok{"Data Leakage Alert: Train and test indices overlap!"} \OtherTok{=} \FunctionTok{length}\NormalTok{(}\FunctionTok{intersect}\NormalTok{(train\_id, test\_id)) }\SpecialCharTok{==} \DecValTok{0}\DataTypeTok{L}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Preflight audit passed: Folds, objects, and leakage boundaries are verified.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Print full R engine, OS, and package version details for reproducibility auditing}
\FunctionTok{sessionInfo}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## R version 4.6.0 (2026-04-24 ucrt)
## Platform: x86_64-w64-mingw32/x64
## Running under: Windows 11 x64 (build 26200)
## 
## Matrix products: default
##   LAPACK version 3.12.1
## 
## locale:
## [1] LC_COLLATE=Vietnamese_Vietnam.utf8  LC_CTYPE=Vietnamese_Vietnam.utf8   
## [3] LC_MONETARY=Vietnamese_Vietnam.utf8 LC_NUMERIC=C                       
## [5] LC_TIME=Vietnamese_Vietnam.utf8    
## 
## time zone: Asia/Saigon
## tzcode source: internal
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] knitr_1.51      broom_1.0.13    glmnet_5.0      Matrix_1.7-5   
##  [5] lubridate_1.9.5 forcats_1.0.1   stringr_1.6.0   dplyr_1.2.1    
##  [9] purrr_1.2.2     readr_2.2.0     tidyr_1.3.2     tibble_3.3.1   
## [13] ggplot2_4.0.3   tidyverse_2.0.0
## 
## loaded via a namespace (and not attached):
##  [1] generics_0.1.4     shape_1.4.6.1      stringi_1.8.7      lattice_0.22-9    
##  [5] hms_1.1.4          digest_0.6.39      magrittr_2.0.5     timechange_0.4.0  
##  [9] evaluate_1.0.5     grid_4.6.0         RColorBrewer_1.1-3 iterators_1.0.14  
## [13] fastmap_1.2.0      foreach_1.5.2      backports_1.5.1    survival_3.8-6    
## [17] scales_1.4.0       codetools_0.2-20   cli_3.6.6          rlang_1.2.0       
## [21] splines_4.6.0      withr_3.0.2        yaml_2.3.12        otel_0.2.0        
## [25] tools_4.6.0        tzdb_0.5.0         vctrs_0.7.3        R6_2.6.1          
## [29] lifecycle_1.0.5    pkgconfig_2.0.3    pillar_1.11.1      gtable_0.3.6      
## [33] glue_1.8.1         Rcpp_1.1.2         xfun_0.58          tidyselect_1.2.1  
## [37] rstudioapi_0.18.0  farver_2.1.2       htmltools_0.5.9    rmarkdown_2.31    
## [41] compiler_4.6.0     S7_0.2.2
\end{verbatim}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{1}{1}
\bibitem[\citeproctext]{ref-krogh1992weightdecay}
Krogh, Anders, and John A. Hertz. 1992. {``A Simple Weight Decay Can
Improve Generalization.''} \emph{Advances in Neural Information
Processing Systems ({NeurIPS})} 4: 950--57.

\bibitem[\citeproctext]{ref-loshchilov2019adamw}
Loshchilov, Ilya, and Frank Hutter. 2019. {``Decoupling Weight Decay
from Gradient-Based Optimizers.''} \emph{International Conference on
Learning Representations ({ICLR})}.

\end{CSLReferences}

\end{document}
